deep-copy-regex:
    - source: /google/cloud/audit/.*-php/(.*)
      dest: /owl-bot-staging/CommonProtos/audit-protos/$1
    - source: /google/devtools/source/v1/.*-php/(.*)
      dest: /owl-bot-staging/CommonProtos/devtools-protos/$1
    - source: /google/cloud/common/.*-php/(.*)
      dest: /owl-bot-staging/CommonProtos/common-protos/$1
api-name: CommonProtos
