<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/gkebackup/v1/restore_plan.proto

namespace Google\Cloud\GkeBackup\V1\RestorePlan;

use UnexpectedValueException;

/**
 * State
 *
 * Protobuf type <code>google.cloud.gkebackup.v1.RestorePlan.State</code>
 */
class State
{
    /**
     * Default first value for Enums.
     *
     * Generated from protobuf enum <code>STATE_UNSPECIFIED = 0;</code>
     */
    const STATE_UNSPECIFIED = 0;
    /**
     * Waiting for cluster state to be RUNNING.
     *
     * Generated from protobuf enum <code>CLUSTER_PENDING = 1;</code>
     */
    const CLUSTER_PENDING = 1;
    /**
     * The RestorePlan has successfully been created and is ready for Restores.
     *
     * Generated from protobuf enum <code>READY = 2;</code>
     */
    const READY = 2;
    /**
     * RestorePlan creation has failed.
     *
     * Generated from protobuf enum <code>FAILED = 3;</code>
     */
    const FAILED = 3;
    /**
     * The RestorePlan is in the process of being deleted.
     *
     * Generated from protobuf enum <code>DELETING = 4;</code>
     */
    const DELETING = 4;

    private static $valueToName = [
        self::STATE_UNSPECIFIED => 'STATE_UNSPECIFIED',
        self::CLUSTER_PENDING => 'CLUSTER_PENDING',
        self::READY => 'READY',
        self::FAILED => 'FAILED',
        self::DELETING => 'DELETING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}


