<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/discoveryengine/v1/conversational_search_service.proto

namespace GPBMetadata\Google\Cloud\Discoveryengine\V1;

class ConversationalSearchService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Cloud\Discoveryengine\V1\Conversation::initOnce();
        \GPBMetadata\Google\Cloud\Discoveryengine\V1\SearchService::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\FieldMask::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ë%
Cgoogle/cloud/discoveryengine/v1/conversational_search_service.protogoogle.cloud.discoveryengine.v1google/api/client.protogoogle/api/field_behavior.protogoogle/api/resource.proto2google/cloud/discoveryengine/v1/conversation.proto4google/cloud/discoveryengine/v1/search_service.protogoogle/protobuf/empty.proto google/protobuf/field_mask.proto"Ï
ConverseConversationRequestA
name (	B3àAúA-
+discoveryengine.googleapis.com/Conversation>
query (2*.google.cloud.discoveryengine.v1.TextInputBàAI
serving_config (	B1úA.
,discoveryengine.googleapis.com/ServingConfigC
conversation (2-.google.cloud.discoveryengine.v1.Conversation
safe_search (a
user_labels (2L.google.cloud.discoveryengine.v1.ConverseConversationRequest.UserLabelsEntryb
summary_spec (2L.google.cloud.discoveryengine.v1.SearchRequest.ContentSearchSpec.SummarySpec
filter	 (	1
UserLabelsEntry
key (	
value (	:8"ð
ConverseConversationResponse5
reply (2&.google.cloud.discoveryengine.v1.ReplyC
conversation (2-.google.cloud.discoveryengine.v1.ConversationT
search_results (2<.google.cloud.discoveryengine.v1.SearchResponse.SearchResult"§
CreateConversationRequest@
parent (	B0àAúA*
(discoveryengine.googleapis.com/DataStoreH
conversation (2-.google.cloud.discoveryengine.v1.ConversationBàA"–
UpdateConversationRequestH
conversation (2-.google.cloud.discoveryengine.v1.ConversationBàA/
update_mask (2.google.protobuf.FieldMask"^
DeleteConversationRequestA
name (	B3àAúA-
+discoveryengine.googleapis.com/Conversation"[
GetConversationRequestA
name (	B3àAúA-
+discoveryengine.googleapis.com/Conversation"¥
ListConversationsRequest@
parent (	B0àAúA*
(discoveryengine.googleapis.com/DataStore
	page_size (

page_token (	
filter (	
order_by (	"z
ListConversationsResponseD
conversations (2-.google.cloud.discoveryengine.v1.Conversation
next_page_token (	2Ý
ConversationalSearchService«
ConverseConversation<.google.cloud.discoveryengine.v1.ConverseConversationRequest=.google.cloud.discoveryengine.v1.ConverseConversationResponse"•ÚA
name,query‚Óä“"G/v1/{name=projects/*/locations/*/dataStores/*/conversations/*}:converse:*ZZ"U/v1/{name=projects/*/locations/*/collections/*/dataStores/*/conversations/*}:converse:*ZW"R/v1/{name=projects/*/locations/*/collections/*/engines/*/conversations/*}:converse:*¦
CreateConversation:.google.cloud.discoveryengine.v1.CreateConversationRequest-.google.cloud.discoveryengine.v1.Conversation"¤ÚAparent,conversation‚Óä“‡">/v1/{parent=projects/*/locations/*/dataStores/*}/conversations:conversationZ\\"L/v1/{parent=projects/*/locations/*/collections/*/dataStores/*}/conversations:conversationZY"I/v1/{parent=projects/*/locations/*/collections/*/engines/*}/conversations:conversationÖ
DeleteConversation:.google.cloud.discoveryengine.v1.DeleteConversationRequest.google.protobuf.Empty"ëÚAname‚Óä“Ý*>/v1/{name=projects/*/locations/*/dataStores/*/conversations/*}ZN*L/v1/{name=projects/*/locations/*/collections/*/dataStores/*/conversations/*}ZK*I/v1/{name=projects/*/locations/*/collections/*/engines/*/conversations/*}Ò
UpdateConversation:.google.cloud.discoveryengine.v1.UpdateConversationRequest-.google.cloud.discoveryengine.v1.Conversation"ÐÚAconversation,update_mask‚Óä“®2K/v1/{conversation.name=projects/*/locations/*/dataStores/*/conversations/*}:conversationZi2Y/v1/{conversation.name=projects/*/locations/*/collections/*/dataStores/*/conversations/*}:conversationZf2V/v1/{conversation.name=projects/*/locations/*/collections/*/engines/*/conversations/*}:conversationç
GetConversation7.google.cloud.discoveryengine.v1.GetConversationRequest-.google.cloud.discoveryengine.v1.Conversation"ëÚAname‚Óä“Ý>/v1/{name=projects/*/locations/*/dataStores/*/conversations/*}ZNL/v1/{name=projects/*/locations/*/collections/*/dataStores/*/conversations/*}ZKI/v1/{name=projects/*/locations/*/collections/*/engines/*/conversations/*}ú
ListConversations9.google.cloud.discoveryengine.v1.ListConversationsRequest:.google.cloud.discoveryengine.v1.ListConversationsResponse"íÚAparent‚Óä“Ý>/v1/{parent=projects/*/locations/*/dataStores/*}/conversationsZNL/v1/{parent=projects/*/locations/*/collections/*/dataStores/*}/conversationsZKI/v1/{parent=projects/*/locations/*/collections/*/engines/*}/conversationsRÊAdiscoveryengine.googleapis.comÒA.https://www.googleapis.com/auth/cloud-platformB“
#com.google.cloud.discoveryengine.v1B ConversationalSearchServiceProtoPZMcloud.google.com/go/discoveryengine/apiv1/discoveryenginepb;discoveryenginepb¢DISCOVERYENGINEªGoogle.Cloud.DiscoveryEngine.V1ÊGoogle\\Cloud\\DiscoveryEngine\\V1ê"Google::Cloud::DiscoveryEngine::V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

