<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/visionai/v1/warehouse.proto

namespace Google\Cloud\VisionAI\V1\Corpus;

use UnexpectedValueException;

/**
 * Type of the asset inside the corpus.
 *
 * Protobuf type <code>google.cloud.visionai.v1.Corpus.Type</code>
 */
class Type
{
    /**
     * The default type, not supposed to be used. If this default type is used,
     * the corpus will be created as STREAM_VIDEO corpus.
     *
     * Generated from protobuf enum <code>TYPE_UNSPECIFIED = 0;</code>
     */
    const TYPE_UNSPECIFIED = 0;
    /**
     * Asset is a live streaming video.
     *
     * Generated from protobuf enum <code>STREAM_VIDEO = 1;</code>
     */
    const STREAM_VIDEO = 1;
    /**
     * Asset is an image.
     *
     * Generated from protobuf enum <code>IMAGE = 2;</code>
     */
    const IMAGE = 2;
    /**
     * Asset is a batch video.
     *
     * Generated from protobuf enum <code>VIDEO_ON_DEMAND = 3;</code>
     */
    const VIDEO_ON_DEMAND = 3;

    private static $valueToName = [
        self::TYPE_UNSPECIFIED => 'TYPE_UNSPECIFIED',
        self::STREAM_VIDEO => 'STREAM_VIDEO',
        self::IMAGE => 'IMAGE',
        self::VIDEO_ON_DEMAND => 'VIDEO_ON_DEMAND',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}


