<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Represents civil time (or occasionally physical time).
 * This type can represent a civil time in one of a few possible ways:
 *  * When utc_offset is set and time_zone is unset: a civil time on a calendar
 *    day with a particular offset from UTC.
 *  * When time_zone is set and utc_offset is unset: a civil time on a calendar
 *    day in a particular time zone.
 *  * When neither time_zone nor utc_offset is set: a civil time on a calendar
 *    day in local time.
 * The date is relative to the Proleptic Gregorian Calendar.
 * If year, month, or day are 0, the DateTime is considered not to have a
 * specific year, month, or day respectively.
 * This type may also be used to represent a physical time if all the date and
 * time fields are set and either case of the `time_offset` oneof is set.
 * Consider using `Timestamp` message for physical time instead. If your use
 * case also would like to store the user's timezone, that can be done in
 * another field.
 * This type is more flexible than some applications may want. Make sure to
 * document and validate your application's limitations.
 *
 * Generated from protobuf message <code>google.cloud.compute.v1.DateTime</code>
 */
class DateTime extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. Day of month. Must be from 1 to 31 and valid for the year and
     * month, or 0 if specifying a datetime without a day.
     *
     * Generated from protobuf field <code>optional int32 day = 99228;</code>
     */
    protected $day = null;
    /**
     * Optional. Hours of day in 24 hour format. Should be from 0 to 23, defaults
     * to 0 (midnight). An API may choose to allow the value "24:00:00" for
     * scenarios like business closing time.
     *
     * Generated from protobuf field <code>optional int32 hours = 99469071;</code>
     */
    protected $hours = null;
    /**
     * Optional. Minutes of hour of day. Must be from 0 to 59, defaults to 0.
     *
     * Generated from protobuf field <code>optional int32 minutes = 528030943;</code>
     */
    protected $minutes = null;
    /**
     * Optional. Month of year. Must be from 1 to 12, or 0 if specifying a
     * datetime without a month.
     *
     * Generated from protobuf field <code>optional int32 month = 104080000;</code>
     */
    protected $month = null;
    /**
     * Optional. Fractions of seconds in nanoseconds. Must be from 0 to
     * 999,999,999, defaults to 0.
     *
     * Generated from protobuf field <code>optional int32 nanos = 104586303;</code>
     */
    protected $nanos = null;
    /**
     * Optional. Seconds of minutes of the time. Must normally be from 0 to 59,
     * defaults to 0. An API may allow the value 60 if it allows leap-seconds.
     *
     * Generated from protobuf field <code>optional int32 seconds = 359484031;</code>
     */
    protected $seconds = null;
    /**
     * Time zone.
     *
     * Generated from protobuf field <code>optional .google.cloud.compute.v1.TimeZone time_zone = 36848094;</code>
     */
    protected $time_zone = null;
    /**
     * UTC offset. Must be whole seconds, between -18 hours and +18 hours.
     * For example, a UTC offset of -4:00 would be represented as
     * { seconds: -14400 }.
     *
     * Generated from protobuf field <code>optional string utc_offset = 89045902;</code>
     */
    protected $utc_offset = null;
    /**
     * Optional. Year of date. Must be from 1 to 9999, or 0 if specifying a
     * datetime without a year.
     *
     * Generated from protobuf field <code>optional int32 year = 3704893;</code>
     */
    protected $year = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $day
     *           Optional. Day of month. Must be from 1 to 31 and valid for the year and
     *           month, or 0 if specifying a datetime without a day.
     *     @type int $hours
     *           Optional. Hours of day in 24 hour format. Should be from 0 to 23, defaults
     *           to 0 (midnight). An API may choose to allow the value "24:00:00" for
     *           scenarios like business closing time.
     *     @type int $minutes
     *           Optional. Minutes of hour of day. Must be from 0 to 59, defaults to 0.
     *     @type int $month
     *           Optional. Month of year. Must be from 1 to 12, or 0 if specifying a
     *           datetime without a month.
     *     @type int $nanos
     *           Optional. Fractions of seconds in nanoseconds. Must be from 0 to
     *           999,999,999, defaults to 0.
     *     @type int $seconds
     *           Optional. Seconds of minutes of the time. Must normally be from 0 to 59,
     *           defaults to 0. An API may allow the value 60 if it allows leap-seconds.
     *     @type \Google\Cloud\Compute\V1\TimeZone $time_zone
     *           Time zone.
     *     @type string $utc_offset
     *           UTC offset. Must be whole seconds, between -18 hours and +18 hours.
     *           For example, a UTC offset of -4:00 would be represented as
     *           { seconds: -14400 }.
     *     @type int $year
     *           Optional. Year of date. Must be from 1 to 9999, or 0 if specifying a
     *           datetime without a year.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. Day of month. Must be from 1 to 31 and valid for the year and
     * month, or 0 if specifying a datetime without a day.
     *
     * Generated from protobuf field <code>optional int32 day = 99228;</code>
     * @return int
     */
    public function getDay()
    {
        return isset($this->day) ? $this->day : 0;
    }

    public function hasDay()
    {
        return isset($this->day);
    }

    public function clearDay()
    {
        unset($this->day);
    }

    /**
     * Optional. Day of month. Must be from 1 to 31 and valid for the year and
     * month, or 0 if specifying a datetime without a day.
     *
     * Generated from protobuf field <code>optional int32 day = 99228;</code>
     * @param int $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkInt32($var);
        $this->day = $var;

        return $this;
    }

    /**
     * Optional. Hours of day in 24 hour format. Should be from 0 to 23, defaults
     * to 0 (midnight). An API may choose to allow the value "24:00:00" for
     * scenarios like business closing time.
     *
     * Generated from protobuf field <code>optional int32 hours = 99469071;</code>
     * @return int
     */
    public function getHours()
    {
        return isset($this->hours) ? $this->hours : 0;
    }

    public function hasHours()
    {
        return isset($this->hours);
    }

    public function clearHours()
    {
        unset($this->hours);
    }

    /**
     * Optional. Hours of day in 24 hour format. Should be from 0 to 23, defaults
     * to 0 (midnight). An API may choose to allow the value "24:00:00" for
     * scenarios like business closing time.
     *
     * Generated from protobuf field <code>optional int32 hours = 99469071;</code>
     * @param int $var
     * @return $this
     */
    public function setHours($var)
    {
        GPBUtil::checkInt32($var);
        $this->hours = $var;

        return $this;
    }

    /**
     * Optional. Minutes of hour of day. Must be from 0 to 59, defaults to 0.
     *
     * Generated from protobuf field <code>optional int32 minutes = 528030943;</code>
     * @return int
     */
    public function getMinutes()
    {
        return isset($this->minutes) ? $this->minutes : 0;
    }

    public function hasMinutes()
    {
        return isset($this->minutes);
    }

    public function clearMinutes()
    {
        unset($this->minutes);
    }

    /**
     * Optional. Minutes of hour of day. Must be from 0 to 59, defaults to 0.
     *
     * Generated from protobuf field <code>optional int32 minutes = 528030943;</code>
     * @param int $var
     * @return $this
     */
    public function setMinutes($var)
    {
        GPBUtil::checkInt32($var);
        $this->minutes = $var;

        return $this;
    }

    /**
     * Optional. Month of year. Must be from 1 to 12, or 0 if specifying a
     * datetime without a month.
     *
     * Generated from protobuf field <code>optional int32 month = 104080000;</code>
     * @return int
     */
    public function getMonth()
    {
        return isset($this->month) ? $this->month : 0;
    }

    public function hasMonth()
    {
        return isset($this->month);
    }

    public function clearMonth()
    {
        unset($this->month);
    }

    /**
     * Optional. Month of year. Must be from 1 to 12, or 0 if specifying a
     * datetime without a month.
     *
     * Generated from protobuf field <code>optional int32 month = 104080000;</code>
     * @param int $var
     * @return $this
     */
    public function setMonth($var)
    {
        GPBUtil::checkInt32($var);
        $this->month = $var;

        return $this;
    }

    /**
     * Optional. Fractions of seconds in nanoseconds. Must be from 0 to
     * 999,999,999, defaults to 0.
     *
     * Generated from protobuf field <code>optional int32 nanos = 104586303;</code>
     * @return int
     */
    public function getNanos()
    {
        return isset($this->nanos) ? $this->nanos : 0;
    }

    public function hasNanos()
    {
        return isset($this->nanos);
    }

    public function clearNanos()
    {
        unset($this->nanos);
    }

    /**
     * Optional. Fractions of seconds in nanoseconds. Must be from 0 to
     * 999,999,999, defaults to 0.
     *
     * Generated from protobuf field <code>optional int32 nanos = 104586303;</code>
     * @param int $var
     * @return $this
     */
    public function setNanos($var)
    {
        GPBUtil::checkInt32($var);
        $this->nanos = $var;

        return $this;
    }

    /**
     * Optional. Seconds of minutes of the time. Must normally be from 0 to 59,
     * defaults to 0. An API may allow the value 60 if it allows leap-seconds.
     *
     * Generated from protobuf field <code>optional int32 seconds = 359484031;</code>
     * @return int
     */
    public function getSeconds()
    {
        return isset($this->seconds) ? $this->seconds : 0;
    }

    public function hasSeconds()
    {
        return isset($this->seconds);
    }

    public function clearSeconds()
    {
        unset($this->seconds);
    }

    /**
     * Optional. Seconds of minutes of the time. Must normally be from 0 to 59,
     * defaults to 0. An API may allow the value 60 if it allows leap-seconds.
     *
     * Generated from protobuf field <code>optional int32 seconds = 359484031;</code>
     * @param int $var
     * @return $this
     */
    public function setSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->seconds = $var;

        return $this;
    }

    /**
     * Time zone.
     *
     * Generated from protobuf field <code>optional .google.cloud.compute.v1.TimeZone time_zone = 36848094;</code>
     * @return \Google\Cloud\Compute\V1\TimeZone|null
     */
    public function getTimeZone()
    {
        return $this->time_zone;
    }

    public function hasTimeZone()
    {
        return isset($this->time_zone);
    }

    public function clearTimeZone()
    {
        unset($this->time_zone);
    }

    /**
     * Time zone.
     *
     * Generated from protobuf field <code>optional .google.cloud.compute.v1.TimeZone time_zone = 36848094;</code>
     * @param \Google\Cloud\Compute\V1\TimeZone $var
     * @return $this
     */
    public function setTimeZone($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Compute\V1\TimeZone::class);
        $this->time_zone = $var;

        return $this;
    }

    /**
     * UTC offset. Must be whole seconds, between -18 hours and +18 hours.
     * For example, a UTC offset of -4:00 would be represented as
     * { seconds: -14400 }.
     *
     * Generated from protobuf field <code>optional string utc_offset = 89045902;</code>
     * @return string
     */
    public function getUtcOffset()
    {
        return isset($this->utc_offset) ? $this->utc_offset : '';
    }

    public function hasUtcOffset()
    {
        return isset($this->utc_offset);
    }

    public function clearUtcOffset()
    {
        unset($this->utc_offset);
    }

    /**
     * UTC offset. Must be whole seconds, between -18 hours and +18 hours.
     * For example, a UTC offset of -4:00 would be represented as
     * { seconds: -14400 }.
     *
     * Generated from protobuf field <code>optional string utc_offset = 89045902;</code>
     * @param string $var
     * @return $this
     */
    public function setUtcOffset($var)
    {
        GPBUtil::checkString($var, True);
        $this->utc_offset = $var;

        return $this;
    }

    /**
     * Optional. Year of date. Must be from 1 to 9999, or 0 if specifying a
     * datetime without a year.
     *
     * Generated from protobuf field <code>optional int32 year = 3704893;</code>
     * @return int
     */
    public function getYear()
    {
        return isset($this->year) ? $this->year : 0;
    }

    public function hasYear()
    {
        return isset($this->year);
    }

    public function clearYear()
    {
        unset($this->year);
    }

    /**
     * Optional. Year of date. Must be from 1 to 9999, or 0 if specifying a
     * datetime without a year.
     *
     * Generated from protobuf field <code>optional int32 year = 3704893;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

}

