<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * HttpRouteRuleMatch criteria for field values that must stay within the specified integer range.
 *
 * Generated from protobuf message <code>google.cloud.compute.v1.Int64RangeMatch</code>
 */
class Int64RangeMatch extends \Google\Protobuf\Internal\Message
{
    /**
     * The end of the range (exclusive) in signed long integer format.
     *
     * Generated from protobuf field <code>string range_end = 54004441;</code>
     */
    private $range_end = '';
    /**
     * The start of the range (inclusive) in signed long integer format.
     *
     * Generated from protobuf field <code>string range_start = 103333600;</code>
     */
    private $range_start = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $range_end
     *           The end of the range (exclusive) in signed long integer format.
     *     @type string $range_start
     *           The start of the range (inclusive) in signed long integer format.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Compute\V1\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * The end of the range (exclusive) in signed long integer format.
     *
     * Generated from protobuf field <code>string range_end = 54004441;</code>
     * @return string
     */
    public function getRangeEnd()
    {
        return $this->range_end;
    }

    /**
     * The end of the range (exclusive) in signed long integer format.
     *
     * Generated from protobuf field <code>string range_end = 54004441;</code>
     * @param string $var
     * @return $this
     */
    public function setRangeEnd($var)
    {
        GPBUtil::checkString($var, True);
        $this->range_end = $var;

        return $this;
    }

    /**
     * The start of the range (inclusive) in signed long integer format.
     *
     * Generated from protobuf field <code>string range_start = 103333600;</code>
     * @return string
     */
    public function getRangeStart()
    {
        return $this->range_start;
    }

    /**
     * The start of the range (inclusive) in signed long integer format.
     *
     * Generated from protobuf field <code>string range_start = 103333600;</code>
     * @param string $var
     * @return $this
     */
    public function setRangeStart($var)
    {
        GPBUtil::checkString($var, True);
        $this->range_start = $var;

        return $this;
    }

}

