<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/securitycenter/v1/container.proto

namespace GPBMetadata\Google\Cloud\Securitycenter\V1;

class Container
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Cloud\Securitycenter\V1\Label::initOnce();
        $pool->internalAddGeneratedFile(
            '
¶
.google/cloud/securitycenter/v1/container.protogoogle.cloud.securitycenter.v1"o
	Container
name (	
uri (	
image_id (	5
labels (2%.google.cloud.securitycenter.v1.LabelBê
"com.google.cloud.securitycenter.v1BContainerProtoPZLgoogle.golang.org/genproto/googleapis/cloud/securitycenter/v1;securitycenterªGoogle.Cloud.SecurityCenter.V1ÊGoogle\\Cloud\\SecurityCenter\\V1ê!Google::Cloud::SecurityCenter::V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

