<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/discoveryengine/v1/search_service.proto

namespace Google\Cloud\DiscoveryEngine\V1\SearchRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Specification to enable natural language understanding capabilities for
 * search requests.
 *
 * Generated from protobuf message <code>google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec</code>
 */
class NaturalLanguageQueryUnderstandingSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * The condition under which filter extraction should occur.
     * Server behavior defaults to `DISABLED`.
     *
     * Generated from protobuf field <code>.google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition filter_extraction_condition = 1;</code>
     */
    protected $filter_extraction_condition = 0;
    /**
     * Field names used for location-based filtering, where geolocation filters
     * are detected in natural language search queries.
     * Only valid when the FilterExtractionCondition is set to `ENABLED`.
     * If this field is set, it overrides the field names set in
     * [ServingConfig.geo_search_query_detection_field_names][google.cloud.discoveryengine.v1.ServingConfig.geo_search_query_detection_field_names].
     *
     * Generated from protobuf field <code>repeated string geo_search_query_detection_field_names = 2;</code>
     */
    private $geo_search_query_detection_field_names;
    /**
     * Optional. Controls behavior of how extracted filters are applied to the
     * search. The default behavior depends on the request. For single datastore
     * structured search, the default is `HARD_FILTER`. For multi-datastore
     * search, the default behavior is `SOFT_BOOST`.
     * Location-based filters are always applied as hard filters, and the
     * `SOFT_BOOST` setting will not affect them.
     * This field is only used if
     * [SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition][google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition]
     * is set to
     * [FilterExtractionCondition.ENABLED][google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition.ENABLED].
     *
     * Generated from protobuf field <code>.google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.ExtractedFilterBehavior extracted_filter_behavior = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $extracted_filter_behavior = 0;
    /**
     * Optional. Allowlist of fields that can be used for natural language
     * filter extraction. By default, if this is unspecified, all indexable
     * fields are eligible for natural language filter extraction (but are not
     * guaranteed to be used). If any fields are specified in
     * allowed_field_names, only the fields that are both marked as indexable in
     * the schema and specified in the allowlist will be eligible for natural
     * language filter extraction. Note: for multi-datastore search, this is not
     * yet supported, and will be ignored.
     *
     * Generated from protobuf field <code>repeated string allowed_field_names = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     */
    private $allowed_field_names;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $filter_extraction_condition
     *           The condition under which filter extraction should occur.
     *           Server behavior defaults to `DISABLED`.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $geo_search_query_detection_field_names
     *           Field names used for location-based filtering, where geolocation filters
     *           are detected in natural language search queries.
     *           Only valid when the FilterExtractionCondition is set to `ENABLED`.
     *           If this field is set, it overrides the field names set in
     *           [ServingConfig.geo_search_query_detection_field_names][google.cloud.discoveryengine.v1.ServingConfig.geo_search_query_detection_field_names].
     *     @type int $extracted_filter_behavior
     *           Optional. Controls behavior of how extracted filters are applied to the
     *           search. The default behavior depends on the request. For single datastore
     *           structured search, the default is `HARD_FILTER`. For multi-datastore
     *           search, the default behavior is `SOFT_BOOST`.
     *           Location-based filters are always applied as hard filters, and the
     *           `SOFT_BOOST` setting will not affect them.
     *           This field is only used if
     *           [SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition][google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition]
     *           is set to
     *           [FilterExtractionCondition.ENABLED][google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition.ENABLED].
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $allowed_field_names
     *           Optional. Allowlist of fields that can be used for natural language
     *           filter extraction. By default, if this is unspecified, all indexable
     *           fields are eligible for natural language filter extraction (but are not
     *           guaranteed to be used). If any fields are specified in
     *           allowed_field_names, only the fields that are both marked as indexable in
     *           the schema and specified in the allowlist will be eligible for natural
     *           language filter extraction. Note: for multi-datastore search, this is not
     *           yet supported, and will be ignored.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Discoveryengine\V1\SearchService::initOnce();
        parent::__construct($data);
    }

    /**
     * The condition under which filter extraction should occur.
     * Server behavior defaults to `DISABLED`.
     *
     * Generated from protobuf field <code>.google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition filter_extraction_condition = 1;</code>
     * @return int
     */
    public function getFilterExtractionCondition()
    {
        return $this->filter_extraction_condition;
    }

    /**
     * The condition under which filter extraction should occur.
     * Server behavior defaults to `DISABLED`.
     *
     * Generated from protobuf field <code>.google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition filter_extraction_condition = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFilterExtractionCondition($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\DiscoveryEngine\V1\SearchRequest\NaturalLanguageQueryUnderstandingSpec\FilterExtractionCondition::class);
        $this->filter_extraction_condition = $var;

        return $this;
    }

    /**
     * Field names used for location-based filtering, where geolocation filters
     * are detected in natural language search queries.
     * Only valid when the FilterExtractionCondition is set to `ENABLED`.
     * If this field is set, it overrides the field names set in
     * [ServingConfig.geo_search_query_detection_field_names][google.cloud.discoveryengine.v1.ServingConfig.geo_search_query_detection_field_names].
     *
     * Generated from protobuf field <code>repeated string geo_search_query_detection_field_names = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGeoSearchQueryDetectionFieldNames()
    {
        return $this->geo_search_query_detection_field_names;
    }

    /**
     * Field names used for location-based filtering, where geolocation filters
     * are detected in natural language search queries.
     * Only valid when the FilterExtractionCondition is set to `ENABLED`.
     * If this field is set, it overrides the field names set in
     * [ServingConfig.geo_search_query_detection_field_names][google.cloud.discoveryengine.v1.ServingConfig.geo_search_query_detection_field_names].
     *
     * Generated from protobuf field <code>repeated string geo_search_query_detection_field_names = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGeoSearchQueryDetectionFieldNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->geo_search_query_detection_field_names = $arr;

        return $this;
    }

    /**
     * Optional. Controls behavior of how extracted filters are applied to the
     * search. The default behavior depends on the request. For single datastore
     * structured search, the default is `HARD_FILTER`. For multi-datastore
     * search, the default behavior is `SOFT_BOOST`.
     * Location-based filters are always applied as hard filters, and the
     * `SOFT_BOOST` setting will not affect them.
     * This field is only used if
     * [SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition][google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition]
     * is set to
     * [FilterExtractionCondition.ENABLED][google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition.ENABLED].
     *
     * Generated from protobuf field <code>.google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.ExtractedFilterBehavior extracted_filter_behavior = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return int
     */
    public function getExtractedFilterBehavior()
    {
        return $this->extracted_filter_behavior;
    }

    /**
     * Optional. Controls behavior of how extracted filters are applied to the
     * search. The default behavior depends on the request. For single datastore
     * structured search, the default is `HARD_FILTER`. For multi-datastore
     * search, the default behavior is `SOFT_BOOST`.
     * Location-based filters are always applied as hard filters, and the
     * `SOFT_BOOST` setting will not affect them.
     * This field is only used if
     * [SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition][google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition]
     * is set to
     * [FilterExtractionCondition.ENABLED][google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.FilterExtractionCondition.ENABLED].
     *
     * Generated from protobuf field <code>.google.cloud.discoveryengine.v1.SearchRequest.NaturalLanguageQueryUnderstandingSpec.ExtractedFilterBehavior extracted_filter_behavior = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param int $var
     * @return $this
     */
    public function setExtractedFilterBehavior($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\DiscoveryEngine\V1\SearchRequest\NaturalLanguageQueryUnderstandingSpec\ExtractedFilterBehavior::class);
        $this->extracted_filter_behavior = $var;

        return $this;
    }

    /**
     * Optional. Allowlist of fields that can be used for natural language
     * filter extraction. By default, if this is unspecified, all indexable
     * fields are eligible for natural language filter extraction (but are not
     * guaranteed to be used). If any fields are specified in
     * allowed_field_names, only the fields that are both marked as indexable in
     * the schema and specified in the allowlist will be eligible for natural
     * language filter extraction. Note: for multi-datastore search, this is not
     * yet supported, and will be ignored.
     *
     * Generated from protobuf field <code>repeated string allowed_field_names = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllowedFieldNames()
    {
        return $this->allowed_field_names;
    }

    /**
     * Optional. Allowlist of fields that can be used for natural language
     * filter extraction. By default, if this is unspecified, all indexable
     * fields are eligible for natural language filter extraction (but are not
     * guaranteed to be used). If any fields are specified in
     * allowed_field_names, only the fields that are both marked as indexable in
     * the schema and specified in the allowlist will be eligible for natural
     * language filter extraction. Note: for multi-datastore search, this is not
     * yet supported, and will be ignored.
     *
     * Generated from protobuf field <code>repeated string allowed_field_names = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllowedFieldNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allowed_field_names = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(NaturalLanguageQueryUnderstandingSpec::class, \Google\Cloud\DiscoveryEngine\V1\SearchRequest_NaturalLanguageQueryUnderstandingSpec::class);

