<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/admanager/v1/live_stream_event_enums.proto

namespace Google\Ads\AdManager\V1\LiveStreamEventStatusEnum;

use UnexpectedValueException;

/**
 * Describes the status of a LiveStreamEvent object.
 *
 * Protobuf type <code>google.ads.admanager.v1.LiveStreamEventStatusEnum.LiveStreamEventStatus</code>
 */
class LiveStreamEventStatus
{
    /**
     * Default value. This value is unused.
     *
     * Generated from protobuf enum <code>LIVE_STREAM_EVENT_STATUS_UNSPECIFIED = 0;</code>
     */
    const LIVE_STREAM_EVENT_STATUS_UNSPECIFIED = 0;
    /**
     * Indicates the LiveStreamEvent has been created and is eligible
     * for streaming.
     *
     * Generated from protobuf enum <code>ACTIVE = 1;</code>
     */
    const ACTIVE = 1;
    /**
     * Indicates that the stream is still being served, but ad insertion should
     * be paused temporarily.
     *
     * Generated from protobuf enum <code>ADS_PAUSED = 2;</code>
     */
    const ADS_PAUSED = 2;
    /**
     * Indicates the LiveStreamEvent has been archived.
     *
     * Generated from protobuf enum <code>ARCHIVED = 3;</code>
     */
    const ARCHIVED = 3;
    /**
     * Indicates the LiveStreamEvent has been paused. This
     * can be made #ACTIVE at later time.
     *
     * Generated from protobuf enum <code>PAUSED = 4;</code>
     */
    const PAUSED = 4;

    private static $valueToName = [
        self::LIVE_STREAM_EVENT_STATUS_UNSPECIFIED => 'LIVE_STREAM_EVENT_STATUS_UNSPECIFIED',
        self::ACTIVE => 'ACTIVE',
        self::ADS_PAUSED => 'ADS_PAUSED',
        self::ARCHIVED => 'ARCHIVED',
        self::PAUSED => 'PAUSED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

