#!/bin/bash

set -ev

function buildDocs () {
  echo "doc dir before generation:"
  find docs
  ./dev/google-cloud docs -r ${TRAVIS_TAG:?"false"}
  echo "doc dir after generation:"
  find docs
}


buildDocs
