#!/bin/bash

mkdir $
export GOPATH=$TRAVIS_BUILD_DIR/go

go get -d github.com/libgit2/git2go
cd $GOPATH/src/github.com/libgit2/git2go
git checkout next
git submodule update --init
make install

go get github.com/splitsh/lite
go build -o $TRAVIS_BUILD_DIR/splitsh-lite github.com/splitsh/lite
