#!/bin/bash

mkdir $1
export GOPATH=$1/go

go get -d github.com/libgit2/git2go
cd $GOPATH/src/github.com/libgit2/git2go
git checkout next
git submodule update --init
make install

go get github.com/splitsh/lite
go build -o $1/splitsh-lite github.com/splitsh/lite
