#!/bin/bash

$(dirname $0)/../google-cloud credentials

# if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
#     $(dirname $0)/../google-cloud credentials
# else
#     echo "Not in a cron job, skipping.";
#     exit 0
# fi
