#!/usr/bin/php
<?php

fwrite(STDOUT, "Setting up system test credentials....\n");

// if (getenv('TRAVIS_EVENT_TYPE') !== 'cron') {
//     fwrite(STDOUT, "Not in a cron job, skipping.\n");
//     exit(0);
// }

$keyfiles = [
    'GOOGLE_CLOUD_PHP_TESTS',
    'GOOGLE_CLOUD_PHP_TESTS_WHITELIST'
];

foreach ($keyfiles as $kf) {
    $err = false;

    $data = json_decode(base64_decode(getenv($kf . '_ENCODED')), true);
    if (json_last_error() !== JSON_ERROR_DEPTH) {
        fwrite(STDOUT, "Required environment variable `". $kf . "_ENCODED` not set or invalid! \n");
        exit(1);
    } else {
        fwrite(STDOUT, "Found valid json at environment variable `". $kf ."`\n");
    }

    $path = getenv('TRAVIS_BUILD_DIR') .'/'. $kf .'.json';
    if (file_put_contents($path, $data) !== false) {
        fwrite(STDOUT, "Wrote keyfile contents to file.\n");
    } else {
        fwrite(STDOUT, "Could not write to file.\n");
        exit(1);
    }
}
