#!/bin/bash

set -e

function unit () {
  echo "Running Unit Test Suite"

  $(dirname $0)/../../vendor/bin/phpunit
}

function system () {
  echo "Running System Test Suite"

  $(dirname $0)/../../vendor/bin/phpunit -c phpunit-system.xml.dist
}

function snippets() {
  echo "Running Snippet Test Suite"

  $(dirname $0)/../../vendor/bin/phpunit -c phpunit-snippets.xml.dist
}

unit
snippets

if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
  system
fi
