<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/admanager/v1/exclusion_scope_enum.proto

namespace Google\Ads\AdManager\V1\ExclusionScopeEnum;

use UnexpectedValueException;

/**
 * The scope to which the exclusion label applies.
 *
 * Protobuf type <code>google.ads.admanager.v1.ExclusionScopeEnum.ExclusionScope</code>
 */
class ExclusionScope
{
    /**
     * No value specified.
     *
     * Generated from protobuf enum <code>EXCLUSION_SCOPE_UNSPECIFIED = 0;</code>
     */
    const EXCLUSION_SCOPE_UNSPECIFIED = 0;
    /**
     * The exclusion label applies to the entire page.
     *
     * Generated from protobuf enum <code>PAGE = 1;</code>
     */
    const PAGE = 1;
    /**
     * The exclusion label applies to the entire stream of content.
     *
     * Generated from protobuf enum <code>STREAM = 2;</code>
     */
    const STREAM = 2;
    /**
     * The exclusion label applies to the entire pod (or group).
     *
     * Generated from protobuf enum <code>POD = 3;</code>
     */
    const POD = 3;

    private static $valueToName = [
        self::EXCLUSION_SCOPE_UNSPECIFIED => 'EXCLUSION_SCOPE_UNSPECIFIED',
        self::PAGE => 'PAGE',
        self::STREAM => 'STREAM',
        self::POD => 'POD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

