deep-copy-regex:
    - source: /google/cloud/billing/budgets/v1/.*-php/(.*)
      dest: /owl-bot-staging/BillingBudgets/v1/$1
    - source: /google/cloud/billing/budgets/v1beta1/.*-php/(.*)
      dest: /owl-bot-staging/BillingBudgets/v1beta1/$1
api-name: BillingBudgets
