#!/usr/bin/env php
<?php
/**
 * Copyright 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

require __DIR__ . '/../vendor/autoload.php';

use Google\Cloud\Dev\AddComponent\Command\AddComponent;
use Google\Cloud\Dev\ComponentIntegration\Command\ComponentIntegration;
use Google\Cloud\Dev\Credentials\Command as Credentials;
use Google\Cloud\Dev\DocGenerator\Command\Docs;
use Google\Cloud\Dev\Release\Release;
use Google\Cloud\Dev\ReleaseBuilder\ReleaseBuilder;
use Google\Cloud\Dev\Split\Command\Split;
use Symfony\Component\Console\Application;

if (!class_exists(Application::class)) {
    throw new RuntimeException(
        'Symfony Console Component not installed. ' .
        'run "composer install" or "composer update", making sure not to ' .
        'exclude dev dependencies, and try again.'
    );
}

$rootDirectory = realpath(__DIR__ . '/../') . '/';
$app = new Application;
$app->add(new AddComponent($rootDirectory));
$app->add(new ComponentIntegration($rootDirectory));
$app->add(new Credentials($rootDirectory));
$app->add(new Docs($rootDirectory));
$app->add(new Release($rootDirectory));
$app->add(new ReleaseBuilder($rootDirectory));
$app->add(new Split($rootDirectory));
$app->run();
