#!/usr/bin/env php
<?php
/**
 * Copyright 2016 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
    exit('run composer in the "dev" directory (e.g. composer install -d dev)');
}

require __DIR__ . '/vendor/autoload.php';

use Google\Cloud\Dev\Command\AddComponentCommand;
use Google\Cloud\Dev\Command\ComponentInfoCommand;
use Google\Cloud\Dev\Command\DocFxCommand;
use Google\Cloud\Dev\Command\RepoInfoCommand;
use Google\Cloud\Dev\Command\ReleaseInfoCommand;
use Google\Cloud\Dev\Command\SplitCommand;
use Symfony\Component\Console\Application;

if (!class_exists(Application::class)) {
    throw new RuntimeException(
        'Symfony Console Component not installed. ' .
        'run "composer install" or "composer update", making sure not to ' .
        'exclude dev dependencies, and try again.'
    );
}

$rootDirectory = realpath(__DIR__ . '/../') . '/';

$app = new Application;
$app->add(new AddComponentCommand($rootDirectory));
$app->add(new ComponentInfoCommand());
$app->add(new DocFxCommand());
$app->add(new RepoInfoCommand());
$app->add(new ReleaseInfoCommand());
$app->add(new SplitCommand($rootDirectory));
$app->run();
