<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/shopping/merchant/products/v1/products_common.proto

namespace Google\Shopping\Merchant\Products\V1\ProductAttributes\Returns;

use UnexpectedValueException;

/**
 * The financial outcome of a return.
 *
 * Protobuf type <code>google.shopping.merchant.products.v1.ProductAttributes.Returns.ReturnOutcome</code>
 */
class ReturnOutcome
{
    /**
     * The return outcome is unspecified.
     *
     * Generated from protobuf enum <code>RETURN_OUTCOME_UNSPECIFIED = 0;</code>
     */
    const RETURN_OUTCOME_UNSPECIFIED = 0;
    /**
     * Customer receives a refund.
     *
     * Generated from protobuf enum <code>REFUND = 1;</code>
     */
    const REFUND = 1;
    /**
     * Customer receives an exchange.
     *
     * Generated from protobuf enum <code>EXCHANGE = 2;</code>
     */
    const EXCHANGE = 2;
    /**
     * Customer receives store credit.
     *
     * Generated from protobuf enum <code>STORE_CREDIT = 3;</code>
     */
    const STORE_CREDIT = 3;

    private static $valueToName = [
        self::RETURN_OUTCOME_UNSPECIFIED => 'RETURN_OUTCOME_UNSPECIFIED',
        self::REFUND => 'REFUND',
        self::EXCHANGE => 'EXCHANGE',
        self::STORE_CREDIT => 'STORE_CREDIT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

