<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/securitycenter/v1/security_health_analytics_custom_module.proto

namespace Google\Cloud\SecurityCenter\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\SecurityCenter\V1\SecurityHealthAnalyticsCustomModule\EnablementState instead.
     * @deprecated
     */
    class SecurityHealthAnalyticsCustomModule_EnablementState {}
}
class_exists(SecurityHealthAnalyticsCustomModule\EnablementState::class);
@trigger_error('Google\Cloud\SecurityCenter\V1\SecurityHealthAnalyticsCustomModule_EnablementState is deprecated and will be removed in a future release. Use Google\Cloud\SecurityCenter\V1\SecurityHealthAnalyticsCustomModule\EnablementState instead', E_USER_DEPRECATED);

