<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/gkebackup/v1/backup.proto

namespace Google\Cloud\GkeBackup\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\GkeBackup\V1\Backup\ClusterMetadata instead.
     * @deprecated
     */
    class Backup_ClusterMetadata {}
}
class_exists(Backup\ClusterMetadata::class);
@trigger_error('Google\Cloud\GkeBackup\V1\Backup_ClusterMetadata is deprecated and will be removed in the next major release. Use Google\Cloud\GkeBackup\V1\Backup\ClusterMetadata instead', E_USER_DEPRECATED);

