<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/datacatalog/v1/dataplex_spec.proto

namespace Google\Cloud\DataCatalog\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Common Dataplex fields.
 *
 * Generated from protobuf message <code>google.cloud.datacatalog.v1.DataplexSpec</code>
 */
class DataplexSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * Fully qualified resource name of an asset in Dataplex, to which the
     * underlying data source (Cloud Storage bucket or BigQuery dataset) of the
     * entity is attached.
     *
     * Generated from protobuf field <code>string asset = 1;</code>
     */
    private $asset = '';
    /**
     * Format of the data.
     *
     * Generated from protobuf field <code>.google.cloud.datacatalog.v1.PhysicalSchema data_format = 2;</code>
     */
    private $data_format = null;
    /**
     * Compression format of the data, e.g., zip, gzip etc.
     *
     * Generated from protobuf field <code>string compression_format = 3;</code>
     */
    private $compression_format = '';
    /**
     * Project ID of the underlying Cloud Storage or BigQuery data. Note that
     * this may not be the same project as the correspondingly Dataplex lake /
     * zone / asset.
     *
     * Generated from protobuf field <code>string project_id = 4;</code>
     */
    private $project_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $asset
     *           Fully qualified resource name of an asset in Dataplex, to which the
     *           underlying data source (Cloud Storage bucket or BigQuery dataset) of the
     *           entity is attached.
     *     @type \Google\Cloud\DataCatalog\V1\PhysicalSchema $data_format
     *           Format of the data.
     *     @type string $compression_format
     *           Compression format of the data, e.g., zip, gzip etc.
     *     @type string $project_id
     *           Project ID of the underlying Cloud Storage or BigQuery data. Note that
     *           this may not be the same project as the correspondingly Dataplex lake /
     *           zone / asset.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Datacatalog\V1\DataplexSpec::initOnce();
        parent::__construct($data);
    }

    /**
     * Fully qualified resource name of an asset in Dataplex, to which the
     * underlying data source (Cloud Storage bucket or BigQuery dataset) of the
     * entity is attached.
     *
     * Generated from protobuf field <code>string asset = 1;</code>
     * @return string
     */
    public function getAsset()
    {
        return $this->asset;
    }

    /**
     * Fully qualified resource name of an asset in Dataplex, to which the
     * underlying data source (Cloud Storage bucket or BigQuery dataset) of the
     * entity is attached.
     *
     * Generated from protobuf field <code>string asset = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAsset($var)
    {
        GPBUtil::checkString($var, True);
        $this->asset = $var;

        return $this;
    }

    /**
     * Format of the data.
     *
     * Generated from protobuf field <code>.google.cloud.datacatalog.v1.PhysicalSchema data_format = 2;</code>
     * @return \Google\Cloud\DataCatalog\V1\PhysicalSchema|null
     */
    public function getDataFormat()
    {
        return $this->data_format;
    }

    public function hasDataFormat()
    {
        return isset($this->data_format);
    }

    public function clearDataFormat()
    {
        unset($this->data_format);
    }

    /**
     * Format of the data.
     *
     * Generated from protobuf field <code>.google.cloud.datacatalog.v1.PhysicalSchema data_format = 2;</code>
     * @param \Google\Cloud\DataCatalog\V1\PhysicalSchema $var
     * @return $this
     */
    public function setDataFormat($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\DataCatalog\V1\PhysicalSchema::class);
        $this->data_format = $var;

        return $this;
    }

    /**
     * Compression format of the data, e.g., zip, gzip etc.
     *
     * Generated from protobuf field <code>string compression_format = 3;</code>
     * @return string
     */
    public function getCompressionFormat()
    {
        return $this->compression_format;
    }

    /**
     * Compression format of the data, e.g., zip, gzip etc.
     *
     * Generated from protobuf field <code>string compression_format = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompressionFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->compression_format = $var;

        return $this;
    }

    /**
     * Project ID of the underlying Cloud Storage or BigQuery data. Note that
     * this may not be the same project as the correspondingly Dataplex lake /
     * zone / asset.
     *
     * Generated from protobuf field <code>string project_id = 4;</code>
     * @return string
     */
    public function getProjectId()
    {
        return $this->project_id;
    }

    /**
     * Project ID of the underlying Cloud Storage or BigQuery data. Note that
     * this may not be the same project as the correspondingly Dataplex lake /
     * zone / asset.
     *
     * Generated from protobuf field <code>string project_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_id = $var;

        return $this;
    }

}

