<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/securitycenter/v1/cloud_dlp_inspection.proto

namespace GPBMetadata\Google\Cloud\Securitycenter\V1;

class CloudDlpInspection
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Resource::initOnce();
        $pool->internalAddGeneratedFile(
            '
á
9google/cloud/securitycenter/v1/cloud_dlp_inspection.protogoogle.cloud.securitycenter.v1"ˆ
CloudDlpInspection3
inspect_job (	BúA
dlp.googleapis.com/DlpJob
	info_type (	
info_type_count (
	full_scan (Bð
"com.google.cloud.securitycenter.v1BCloudDlpInspectionProtoPZJcloud.google.com/go/securitycenter/apiv1/securitycenterpb;securitycenterpbªGoogle.Cloud.SecurityCenter.V1ÊGoogle\\Cloud\\SecurityCenter\\V1ê!Google::Cloud::SecurityCenter::V1êA|
dlp.googleapis.com/DlpJob$projects/{project}/dlpJobs/{dlp_job}9projects/{project}/locations/{location}/dlpJobs/{dlp_job}bproto3'
        , true);

        static::$is_initialized = true;
    }
}

