<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/artifactregistry/v1/attachment.proto

namespace GPBMetadata\Google\Devtools\Artifactregistry\V1;

class Attachment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
Û
4google/devtools/artifactregistry/v1/attachment.proto#google.devtools.artifactregistry.v1google/api/resource.protogoogle/protobuf/timestamp.proto"¬

Attachment
name (	
target (	B‡A
type (	
attachment_namespace (	Z
annotations (2@.google.devtools.artifactregistry.v1.Attachment.AnnotationsEntryB‡A4
create_time (2.google.protobuf.TimestampB‡A4
update_time (2.google.protobuf.TimestampB‡A;
files (	B,‡A˙A&
$artifactregistry.googleapis.com/File
oci_version_name	 (	B‡A2
AnnotationsEntry
key (	
value (	:8:åÍAà
*artifactregistry.googleapis.com/AttachmentZprojects/{project}/locations/{location}/repositories/{repository}/attachments/{attachment}"ò
ListAttachmentsRequestB
parent (	B2‡A˙A,*artifactregistry.googleapis.com/Attachment
filter (	B‡A
	page_size (

page_token (	"x
ListAttachmentsResponseD
attachments (2/.google.devtools.artifactregistry.v1.Attachment
next_page_token (	"X
GetAttachmentRequest@
name (	B2‡A˙A,
*artifactregistry.googleapis.com/Attachment"√
CreateAttachmentRequestB
parent (	B2‡A˙A,*artifactregistry.googleapis.com/Attachment
attachment_id (	B‡AH

attachment (2/.google.devtools.artifactregistry.v1.AttachmentB‡A"[
DeleteAttachmentRequest@
name (	B2‡A˙A,
*artifactregistry.googleapis.com/AttachmentB˙
\'com.google.devtools.artifactregistry.v1BAttachmentProtoPZPcloud.google.com/go/artifactregistry/apiv1/artifactregistrypb;artifactregistrypb™ Google.Cloud.ArtifactRegistry.V1  Google\\Cloud\\ArtifactRegistry\\V1Í#Google::Cloud::ArtifactRegistry::V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

