<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/chronicle/v1/feed.proto

namespace Google\Cloud\Chronicle\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Settings required by Amazon Kinesis Firehose Feeds(HTTP-Push).
 *
 * Generated from protobuf message <code>google.cloud.chronicle.v1.AmazonKinesisFirehoseSettings</code>
 */
class AmazonKinesisFirehoseSettings extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Chronicle\V1\Feed::initOnce();
        parent::__construct($data);
    }

}

