<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/tasks/v2/cloudtasks.proto

namespace GPBMetadata\Google\Cloud\Tasks\V2;

class Cloudtasks
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Cloud\Tasks\V2\Queue::initOnce();
        \GPBMetadata\Google\Cloud\Tasks\V2\Task::initOnce();
        \GPBMetadata\Google\Iam\V1\IamPolicy::initOnce();
        \GPBMetadata\Google\Iam\V1\Policy::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\FieldMask::initOnce();
        $pool->internalAddGeneratedFile(
            '
˜%
&google/cloud/tasks/v2/cloudtasks.protogoogle.cloud.tasks.v2google/api/client.protogoogle/api/field_behavior.protogoogle/api/resource.proto!google/cloud/tasks/v2/queue.proto google/cloud/tasks/v2/task.protogoogle/iam/v1/iam_policy.protogoogle/iam/v1/policy.protogoogle/protobuf/empty.proto google/protobuf/field_mask.proto"ƒ
ListQueuesRequest7
parent (	B\'àAúA!cloudtasks.googleapis.com/Queue
filter (	
	page_size (

page_token (	"[
ListQueuesResponse,
queues (2.google.cloud.tasks.v2.Queue
next_page_token (	"H
GetQueueRequest5
name (	B\'àAúA!
cloudtasks.googleapis.com/Queue"
CreateQueueRequest7
parent (	B\'àAúA!cloudtasks.googleapis.com/Queue0
queue (2.google.cloud.tasks.v2.QueueBàA"w
UpdateQueueRequest0
queue (2.google.cloud.tasks.v2.QueueBàA/
update_mask (2.google.protobuf.FieldMask"K
DeleteQueueRequest5
name (	B\'àAúA!
cloudtasks.googleapis.com/Queue"J
PurgeQueueRequest5
name (	B\'àAúA!
cloudtasks.googleapis.com/Queue"J
PauseQueueRequest5
name (	B\'àAúA!
cloudtasks.googleapis.com/Queue"K
ResumeQueueRequest5
name (	B\'àAúA!
cloudtasks.googleapis.com/Queue"ª
ListTasksRequest6
parent (	B&àAúA cloudtasks.googleapis.com/Task7
response_view (2 .google.cloud.tasks.v2.Task.View
	page_size (

page_token (	"X
ListTasksResponse*
tasks (2.google.cloud.tasks.v2.Task
next_page_token (	"
GetTaskRequest4
name (	B&àAúA 
cloudtasks.googleapis.com/Task7
response_view (2 .google.cloud.tasks.v2.Task.View"´
CreateTaskRequest6
parent (	B&àAúA cloudtasks.googleapis.com/Task.
task (2.google.cloud.tasks.v2.TaskBàA7
response_view (2 .google.cloud.tasks.v2.Task.View"I
DeleteTaskRequest4
name (	B&àAúA 
cloudtasks.googleapis.com/Task"
RunTaskRequest4
name (	B&àAúA 
cloudtasks.googleapis.com/Task7
response_view (2 .google.cloud.tasks.v2.Task.View2Ý

CloudTasksž

ListQueues(.google.cloud.tasks.v2.ListQueuesRequest).google.cloud.tasks.v2.ListQueuesResponse";ÚAparent‚Óä“,*/v2/{parent=projects/*/locations/*}/queues‹
GetQueue&.google.cloud.tasks.v2.GetQueueRequest.google.cloud.tasks.v2.Queue"9ÚAname‚Óä“,*/v2/{name=projects/*/locations/*/queues/*} 
CreateQueue).google.cloud.tasks.v2.CreateQueueRequest.google.cloud.tasks.v2.Queue"HÚAparent,queue‚Óä“3"*/v2/{parent=projects/*/locations/*}/queues:queue«
UpdateQueue).google.cloud.tasks.v2.UpdateQueueRequest.google.cloud.tasks.v2.Queue"SÚAqueue,update_mask‚Óä“920/v2/{queue.name=projects/*/locations/*/queues/*}:queue‹
DeleteQueue).google.cloud.tasks.v2.DeleteQueueRequest.google.protobuf.Empty"9ÚAname‚Óä“,**/v2/{name=projects/*/locations/*/queues/*}˜

PurgeQueue(.google.cloud.tasks.v2.PurgeQueueRequest.google.cloud.tasks.v2.Queue"BÚAname‚Óä“5"0/v2/{name=projects/*/locations/*/queues/*}:purge:*˜

PauseQueue(.google.cloud.tasks.v2.PauseQueueRequest.google.cloud.tasks.v2.Queue"BÚAname‚Óä“5"0/v2/{name=projects/*/locations/*/queues/*}:pause:*›
ResumeQueue).google.cloud.tasks.v2.ResumeQueueRequest.google.cloud.tasks.v2.Queue"CÚAname‚Óä“6"1/v2/{name=projects/*/locations/*/queues/*}:resume:*œ
GetIamPolicy".google.iam.v1.GetIamPolicyRequest.google.iam.v1.Policy"QÚAresource‚Óä“@";/v2/{resource=projects/*/locations/*/queues/*}:getIamPolicy:*£
SetIamPolicy".google.iam.v1.SetIamPolicyRequest.google.iam.v1.Policy"XÚAresource,policy‚Óä“@";/v2/{resource=projects/*/locations/*/queues/*}:setIamPolicy:*Î
TestIamPermissions(.google.iam.v1.TestIamPermissionsRequest).google.iam.v1.TestIamPermissionsResponse"cÚAresource,permissions‚Óä“F"A/v2/{resource=projects/*/locations/*/queues/*}:testIamPermissions:*£
	ListTasks\'.google.cloud.tasks.v2.ListTasksRequest(.google.cloud.tasks.v2.ListTasksResponse"CÚAparent‚Óä“42/v2/{parent=projects/*/locations/*/queues/*}/tasks
GetTask%.google.cloud.tasks.v2.GetTaskRequest.google.cloud.tasks.v2.Task"AÚAname‚Óä“42/v2/{name=projects/*/locations/*/queues/*/tasks/*} 

CreateTask(.google.cloud.tasks.v2.CreateTaskRequest.google.cloud.tasks.v2.Task"KÚAparent,task‚Óä“7"2/v2/{parent=projects/*/locations/*/queues/*}/tasks:*‘

DeleteTask(.google.cloud.tasks.v2.DeleteTaskRequest.google.protobuf.Empty"AÚAname‚Óä“4*2/v2/{name=projects/*/locations/*/queues/*/tasks/*}—
RunTask%.google.cloud.tasks.v2.RunTaskRequest.google.cloud.tasks.v2.Task"HÚAname‚Óä“;"6/v2/{name=projects/*/locations/*/queues/*/tasks/*}:run:*MÊAcloudtasks.googleapis.comÒA.https://www.googleapis.com/auth/cloud-platformBv
com.google.cloud.tasks.v2BCloudTasksProtoPZ>cloud.google.com/go/cloudtasks/apiv2/cloudtaskspb;cloudtaskspb¢TASKSbproto3'
        , true);

        static::$is_initialized = true;
    }
}

