<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/artifactregistry/v1beta2/file.proto

namespace Google\Cloud\ArtifactRegistry\V1beta2;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\ArtifactRegistry\V1beta2\Hash\HashType instead.
     * @deprecated
     */
    class Hash_HashType {}
}
class_exists(Hash\HashType::class);
@trigger_error('Google\Cloud\ArtifactRegistry\V1beta2\Hash_HashType is deprecated and will be removed in a future release. Use Google\Cloud\ArtifactRegistry\V1beta2\Hash\HashType instead', E_USER_DEPRECATED);

