<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/compute/v1/compute.proto

namespace Google\Cloud\Compute\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Compute\V1\AllocationSpecificSKUAllocationAllocatedInstancePropertiesReservedDisk\PBInterface instead.
     * @deprecated
     */
    class AllocationSpecificSKUAllocationAllocatedInstancePropertiesReservedDisk_Interface {}
}
class_exists(AllocationSpecificSKUAllocationAllocatedInstancePropertiesReservedDisk\PBInterface::class);
@trigger_error('Google\Cloud\Compute\V1\AllocationSpecificSKUAllocationAllocatedInstancePropertiesReservedDisk_Interface is deprecated and will be removed in the next major release. Use Google\Cloud\Compute\V1\AllocationSpecificSKUAllocationAllocatedInstancePropertiesReservedDisk\PBInterface instead', E_USER_DEPRECATED);

