<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/chronicle/v1/dashboard_chart.proto

namespace Google\Cloud\Chronicle\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request message to get a dashboard chart.
 *
 * Generated from protobuf message <code>google.cloud.chronicle.v1.GetDashboardChartRequest</code>
 */
class GetDashboardChartRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The name of the dashboardChart to retrieve.
     * Format:
     * projects/{project}/locations/{location}/instances/{instance}/dashboardCharts/{chart}
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $name = '';

    /**
     * @param string $name Required. The name of the dashboardChart to retrieve.
     *                     Format:
     *                     projects/{project}/locations/{location}/instances/{instance}/dashboardCharts/{chart}
     *                     Please see {@see DashboardChartServiceClient::dashboardChartName()} for help formatting this field.
     *
     * @return \Google\Cloud\Chronicle\V1\GetDashboardChartRequest
     *
     * @experimental
     */
    public static function build(string $name): self
    {
        return (new self())
            ->setName($name);
    }

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Required. The name of the dashboardChart to retrieve.
     *           Format:
     *           projects/{project}/locations/{location}/instances/{instance}/dashboardCharts/{chart}
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Chronicle\V1\DashboardChart::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The name of the dashboardChart to retrieve.
     * Format:
     * projects/{project}/locations/{location}/instances/{instance}/dashboardCharts/{chart}
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Required. The name of the dashboardChart to retrieve.
     * Format:
     * projects/{project}/locations/{location}/instances/{instance}/dashboardCharts/{chart}
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

