<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dataplex/v1/logs.proto

namespace Google\Cloud\Dataplex\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Dataplex\V1\DiscoveryEvent\ConfigDetails instead.
     * @deprecated
     */
    class DiscoveryEvent_ConfigDetails {}
}
class_exists(DiscoveryEvent\ConfigDetails::class);
@trigger_error('Google\Cloud\Dataplex\V1\DiscoveryEvent_ConfigDetails is deprecated and will be removed in the next major release. Use Google\Cloud\Dataplex\V1\DiscoveryEvent\ConfigDetails instead', E_USER_DEPRECATED);

