<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/networkservices/v1/dep.proto

namespace Google\Cloud\NetworkServices\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message for response to listing `LbRouteExtension` resources.
 *
 * Generated from protobuf message <code>google.cloud.networkservices.v1.ListLbRouteExtensionsResponse</code>
 */
class ListLbRouteExtensionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of `LbRouteExtension` resources.
     *
     * Generated from protobuf field <code>repeated .google.cloud.networkservices.v1.LbRouteExtension lb_route_extensions = 1;</code>
     */
    private $lb_route_extensions;
    /**
     * A token identifying a page of results that the server returns.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';
    /**
     * Locations that could not be reached.
     *
     * Generated from protobuf field <code>repeated string unreachable = 3;</code>
     */
    private $unreachable;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Google\Cloud\NetworkServices\V1\LbRouteExtension>|\Google\Protobuf\Internal\RepeatedField $lb_route_extensions
     *           The list of `LbRouteExtension` resources.
     *     @type string $next_page_token
     *           A token identifying a page of results that the server returns.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $unreachable
     *           Locations that could not be reached.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Networkservices\V1\Dep::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of `LbRouteExtension` resources.
     *
     * Generated from protobuf field <code>repeated .google.cloud.networkservices.v1.LbRouteExtension lb_route_extensions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLbRouteExtensions()
    {
        return $this->lb_route_extensions;
    }

    /**
     * The list of `LbRouteExtension` resources.
     *
     * Generated from protobuf field <code>repeated .google.cloud.networkservices.v1.LbRouteExtension lb_route_extensions = 1;</code>
     * @param array<\Google\Cloud\NetworkServices\V1\LbRouteExtension>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLbRouteExtensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\NetworkServices\V1\LbRouteExtension::class);
        $this->lb_route_extensions = $arr;

        return $this;
    }

    /**
     * A token identifying a page of results that the server returns.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * A token identifying a page of results that the server returns.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

    /**
     * Locations that could not be reached.
     *
     * Generated from protobuf field <code>repeated string unreachable = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnreachable()
    {
        return $this->unreachable;
    }

    /**
     * Locations that could not be reached.
     *
     * Generated from protobuf field <code>repeated string unreachable = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnreachable($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->unreachable = $arr;

        return $this;
    }

}

