<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/shopping/merchant/accounts/v1beta/lfpproviders.proto

namespace Google\Shopping\Merchant\Accounts\V1beta;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request message for the LinkLfpProvider method.
 *
 * Generated from protobuf message <code>google.shopping.merchant.accounts.v1beta.LinkLfpProviderRequest</code>
 */
class LinkLfpProviderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The name of the LFP provider resource to link.
     * Format:
     * `accounts/{account}/omnichannelSettings/{omnichannel_setting}/lfpProviders/{lfp_provider}`.
     * The `lfp_provider` is the LFP provider ID.
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $name = '';
    /**
     * Required. The external account ID by which this merchant is known to the
     * LFP provider.
     *
     * Generated from protobuf field <code>string external_account_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $external_account_id = '';

    /**
     * @param string $name Required. The name of the LFP provider resource to link.
     *                     Format:
     *                     `accounts/{account}/omnichannelSettings/{omnichannel_setting}/lfpProviders/{lfp_provider}`.
     *                     The `lfp_provider` is the LFP provider ID. Please see
     *                     {@see LfpProvidersServiceClient::lfpProviderName()} for help formatting this field.
     *
     * @return \Google\Shopping\Merchant\Accounts\V1beta\LinkLfpProviderRequest
     *
     * @experimental
     */
    public static function build(string $name): self
    {
        return (new self())
            ->setName($name);
    }

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Required. The name of the LFP provider resource to link.
     *           Format:
     *           `accounts/{account}/omnichannelSettings/{omnichannel_setting}/lfpProviders/{lfp_provider}`.
     *           The `lfp_provider` is the LFP provider ID.
     *     @type string $external_account_id
     *           Required. The external account ID by which this merchant is known to the
     *           LFP provider.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Shopping\Merchant\Accounts\V1Beta\Lfpproviders::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The name of the LFP provider resource to link.
     * Format:
     * `accounts/{account}/omnichannelSettings/{omnichannel_setting}/lfpProviders/{lfp_provider}`.
     * The `lfp_provider` is the LFP provider ID.
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Required. The name of the LFP provider resource to link.
     * Format:
     * `accounts/{account}/omnichannelSettings/{omnichannel_setting}/lfpProviders/{lfp_provider}`.
     * The `lfp_provider` is the LFP provider ID.
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Required. The external account ID by which this merchant is known to the
     * LFP provider.
     *
     * Generated from protobuf field <code>string external_account_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getExternalAccountId()
    {
        return $this->external_account_id;
    }

    /**
     * Required. The external account ID by which this merchant is known to the
     * LFP provider.
     *
     * Generated from protobuf field <code>string external_account_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setExternalAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->external_account_id = $var;

        return $this;
    }

}

