<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/deploy/v1/cloud_deploy.proto

namespace Google\Cloud\Deploy\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Configuration of the environment to use when calling Skaffold.
 *
 * Generated from protobuf message <code>google.cloud.deploy.v1.ExecutionConfig</code>
 */
class ExecutionConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. Usages when this configuration should be applied.
     *
     * Generated from protobuf field <code>repeated .google.cloud.deploy.v1.ExecutionConfig.ExecutionEnvironmentUsage usages = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private $usages;
    protected $execution_environment;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $usages
     *           Required. Usages when this configuration should be applied.
     *     @type \Google\Cloud\Deploy\V1\DefaultPool $default_pool
     *           Optional. Use default Cloud Build pool.
     *     @type \Google\Cloud\Deploy\V1\PrivatePool $private_pool
     *           Optional. Use private Cloud Build pool.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Deploy\V1\CloudDeploy::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. Usages when this configuration should be applied.
     *
     * Generated from protobuf field <code>repeated .google.cloud.deploy.v1.ExecutionConfig.ExecutionEnvironmentUsage usages = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsages()
    {
        return $this->usages;
    }

    /**
     * Required. Usages when this configuration should be applied.
     *
     * Generated from protobuf field <code>repeated .google.cloud.deploy.v1.ExecutionConfig.ExecutionEnvironmentUsage usages = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Google\Cloud\Deploy\V1\ExecutionConfig\ExecutionEnvironmentUsage::class);
        $this->usages = $arr;

        return $this;
    }

    /**
     * Optional. Use default Cloud Build pool.
     *
     * Generated from protobuf field <code>.google.cloud.deploy.v1.DefaultPool default_pool = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return \Google\Cloud\Deploy\V1\DefaultPool|null
     */
    public function getDefaultPool()
    {
        return $this->readOneof(2);
    }

    public function hasDefaultPool()
    {
        return $this->hasOneof(2);
    }

    /**
     * Optional. Use default Cloud Build pool.
     *
     * Generated from protobuf field <code>.google.cloud.deploy.v1.DefaultPool default_pool = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param \Google\Cloud\Deploy\V1\DefaultPool $var
     * @return $this
     */
    public function setDefaultPool($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Deploy\V1\DefaultPool::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Optional. Use private Cloud Build pool.
     *
     * Generated from protobuf field <code>.google.cloud.deploy.v1.PrivatePool private_pool = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return \Google\Cloud\Deploy\V1\PrivatePool|null
     */
    public function getPrivatePool()
    {
        return $this->readOneof(3);
    }

    public function hasPrivatePool()
    {
        return $this->hasOneof(3);
    }

    /**
     * Optional. Use private Cloud Build pool.
     *
     * Generated from protobuf field <code>.google.cloud.deploy.v1.PrivatePool private_pool = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param \Google\Cloud\Deploy\V1\PrivatePool $var
     * @return $this
     */
    public function setPrivatePool($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Deploy\V1\PrivatePool::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getExecutionEnvironment()
    {
        return $this->whichOneof("execution_environment");
    }

}

