deep-copy-regex:
    - source: /google/cloud/workflows/(v1|v1beta)/.*-php/(.*)
      dest: /owl-bot-staging/Workflows/$1/$2
    - source: /google/cloud/workflows/executions/(v1|v1beta)/.*-php/(.*)
      dest: /owl-bot-staging/Workflows/Executions/$1/$2
api-name: Workflows
