<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/kms/v1/service.proto

namespace Google\Cloud\Kms\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request message for
 * [KeyManagementService.ListRetiredResources][google.cloud.kms.v1.KeyManagementService.ListRetiredResources].
 *
 * Generated from protobuf message <code>google.cloud.kms.v1.ListRetiredResourcesRequest</code>
 */
class ListRetiredResourcesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The project-specific location holding the
     * [RetiredResources][google.cloud.kms.v1.RetiredResource], in the format
     * `projects/&#42;&#47;locations/&#42;`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $parent = '';
    /**
     * Optional. Optional limit on the number of
     * [RetiredResources][google.cloud.kms.v1.RetiredResource] to be included in
     * the response. Further
     * [RetiredResources][google.cloud.kms.v1.RetiredResource] can subsequently be
     * obtained by including the
     * [ListRetiredResourcesResponse.next_page_token][google.cloud.kms.v1.ListRetiredResourcesResponse.next_page_token]
     * in a subsequent request. If unspecified, the server will pick an
     * appropriate default.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $page_size = 0;
    /**
     * Optional. Optional pagination token, returned earlier via
     * [ListRetiredResourcesResponse.next_page_token][google.cloud.kms.v1.ListRetiredResourcesResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $page_token = '';

    /**
     * @param string $parent Required. The project-specific location holding the
     *                       [RetiredResources][google.cloud.kms.v1.RetiredResource], in the format
     *                       `projects/&#42;/locations/*`. Please see
     *                       {@see KeyManagementServiceClient::locationName()} for help formatting this field.
     *
     * @return \Google\Cloud\Kms\V1\ListRetiredResourcesRequest
     *
     * @experimental
     */
    public static function build(string $parent): self
    {
        return (new self())
            ->setParent($parent);
    }

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The project-specific location holding the
     *           [RetiredResources][google.cloud.kms.v1.RetiredResource], in the format
     *           `projects/&#42;&#47;locations/&#42;`.
     *     @type int $page_size
     *           Optional. Optional limit on the number of
     *           [RetiredResources][google.cloud.kms.v1.RetiredResource] to be included in
     *           the response. Further
     *           [RetiredResources][google.cloud.kms.v1.RetiredResource] can subsequently be
     *           obtained by including the
     *           [ListRetiredResourcesResponse.next_page_token][google.cloud.kms.v1.ListRetiredResourcesResponse.next_page_token]
     *           in a subsequent request. If unspecified, the server will pick an
     *           appropriate default.
     *     @type string $page_token
     *           Optional. Optional pagination token, returned earlier via
     *           [ListRetiredResourcesResponse.next_page_token][google.cloud.kms.v1.ListRetiredResourcesResponse.next_page_token].
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Kms\V1\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The project-specific location holding the
     * [RetiredResources][google.cloud.kms.v1.RetiredResource], in the format
     * `projects/&#42;&#47;locations/&#42;`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The project-specific location holding the
     * [RetiredResources][google.cloud.kms.v1.RetiredResource], in the format
     * `projects/&#42;&#47;locations/&#42;`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Optional. Optional limit on the number of
     * [RetiredResources][google.cloud.kms.v1.RetiredResource] to be included in
     * the response. Further
     * [RetiredResources][google.cloud.kms.v1.RetiredResource] can subsequently be
     * obtained by including the
     * [ListRetiredResourcesResponse.next_page_token][google.cloud.kms.v1.ListRetiredResourcesResponse.next_page_token]
     * in a subsequent request. If unspecified, the server will pick an
     * appropriate default.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Optional. Optional limit on the number of
     * [RetiredResources][google.cloud.kms.v1.RetiredResource] to be included in
     * the response. Further
     * [RetiredResources][google.cloud.kms.v1.RetiredResource] can subsequently be
     * obtained by including the
     * [ListRetiredResourcesResponse.next_page_token][google.cloud.kms.v1.ListRetiredResourcesResponse.next_page_token]
     * in a subsequent request. If unspecified, the server will pick an
     * appropriate default.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Optional. Optional pagination token, returned earlier via
     * [ListRetiredResourcesResponse.next_page_token][google.cloud.kms.v1.ListRetiredResourcesResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Optional. Optional pagination token, returned earlier via
     * [ListRetiredResourcesResponse.next_page_token][google.cloud.kms.v1.ListRetiredResourcesResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

}

