<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/sql/v1beta4/cloud_sql_iam_policies.proto

namespace GPBMetadata\Google\Cloud\Sql\V1Beta4;

class CloudSqlIamPolicies
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        $pool->internalAddGeneratedFile(
            '
“
5google/cloud/sql/v1beta4/cloud_sql_iam_policies.protogoogle.cloud.sql.v1beta4google/api/client.proto23
SqlIamPoliciesServiceÊAsqladmin.googleapis.comBj
com.google.cloud.sql.v1beta4BCloudSqlIamPoliciesProtoPZ.cloud.google.com/go/sql/apiv1beta4/sqlpb;sqlpbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

