<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/alloydb/v1beta/resources.proto

namespace Google\Cloud\AlloyDb\V1beta;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\AlloyDb\V1beta\Instance\State instead.
     * @deprecated
     */
    class Instance_State {}
}
class_exists(Instance\State::class);
@trigger_error('Google\Cloud\AlloyDb\V1beta\Instance_State is deprecated and will be removed in the next major release. Use Google\Cloud\AlloyDb\V1beta\Instance\State instead', E_USER_DEPRECATED);

