<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/maintenance/api/v1/maintenance_service.proto

namespace Google\Cloud\Maintenance\Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MaintenanceSummary contains maintenance statistics calculated based on
 * ResourceMaintenances within the scope: project and location.
 *
 * Generated from protobuf message <code>google.cloud.maintenance.api.v1.MaintenanceSummary</code>
 */
class MaintenanceSummary extends \Google\Protobuf\Internal\Message
{
    /**
     * Output only. The name of the maintenance.
     *
     * Generated from protobuf field <code>string maintenance_name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $maintenance_name = '';
    /**
     * Output only. The title of the maintenance.
     *
     * Generated from protobuf field <code>string title = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $title = '';
    /**
     * Output only. The description of the maintenance.
     *
     * Generated from protobuf field <code>string description = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $description = '';
    /**
     * Output only. The category of the maintenance event.
     *
     * Generated from protobuf field <code>.google.cloud.maintenance.api.v1.MaintenanceCategory category = 13 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $category = 0;
    /**
     * Output only. Scheduled start time of the maintenance. The maintenance will
     * start at `maintenanceScheduledStartTime` or later, with best effort to
     * finish before `maintenanceScheduledEndTime`.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_scheduled_start_time = 6 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $maintenance_scheduled_start_time = null;
    /**
     * Output only. An estimated (best effort, not guaranteed) end time of the
     * scheduled maintenance.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_scheduled_end_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $maintenance_scheduled_end_time = null;
    /**
     * Output only. Actual date when the maintenance started. Field present only
     * after the state changed to `RUNNING`.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_start_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $maintenance_start_time = null;
    /**
     * Output only. Actual date when the maintenance successfully completed. Field
     * present only after the state changed to `SUCCEEDED`.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_end_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $maintenance_end_time = null;
    /**
     * Output only. Indicates whether the user has some control over that
     * maintenance, either proactively before maintenance was scheduled with
     * maintenance policy or with reactive controls after it was scheduled (see
     * controls field).
     *
     * Generated from protobuf field <code>bool user_controllable = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $user_controllable = false;
    /**
     * Output only. Control available for that Maintenance (might not be available
     * for every resource that maintenance is applied to).
     *
     * Generated from protobuf field <code>repeated .google.cloud.maintenance.api.v1.MaintenanceControl controls = 14 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    private $controls;
    /**
     * Output only. Stats is a field of ResourceMaintenance used to aggregate the
     * stats.
     *
     * Generated from protobuf field <code>repeated .google.cloud.maintenance.api.v1.MaintenanceSummary.Stats stats = 12 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    private $stats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $maintenance_name
     *           Output only. The name of the maintenance.
     *     @type string $title
     *           Output only. The title of the maintenance.
     *     @type string $description
     *           Output only. The description of the maintenance.
     *     @type int $category
     *           Output only. The category of the maintenance event.
     *     @type \Google\Protobuf\Timestamp $maintenance_scheduled_start_time
     *           Output only. Scheduled start time of the maintenance. The maintenance will
     *           start at `maintenanceScheduledStartTime` or later, with best effort to
     *           finish before `maintenanceScheduledEndTime`.
     *     @type \Google\Protobuf\Timestamp $maintenance_scheduled_end_time
     *           Output only. An estimated (best effort, not guaranteed) end time of the
     *           scheduled maintenance.
     *     @type \Google\Protobuf\Timestamp $maintenance_start_time
     *           Output only. Actual date when the maintenance started. Field present only
     *           after the state changed to `RUNNING`.
     *     @type \Google\Protobuf\Timestamp $maintenance_end_time
     *           Output only. Actual date when the maintenance successfully completed. Field
     *           present only after the state changed to `SUCCEEDED`.
     *     @type bool $user_controllable
     *           Output only. Indicates whether the user has some control over that
     *           maintenance, either proactively before maintenance was scheduled with
     *           maintenance policy or with reactive controls after it was scheduled (see
     *           controls field).
     *     @type array<\Google\Cloud\Maintenance\Api\V1\MaintenanceControl>|\Google\Protobuf\Internal\RepeatedField $controls
     *           Output only. Control available for that Maintenance (might not be available
     *           for every resource that maintenance is applied to).
     *     @type array<\Google\Cloud\Maintenance\Api\V1\MaintenanceSummary\Stats>|\Google\Protobuf\Internal\RepeatedField $stats
     *           Output only. Stats is a field of ResourceMaintenance used to aggregate the
     *           stats.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Maintenance\Api\V1\MaintenanceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Output only. The name of the maintenance.
     *
     * Generated from protobuf field <code>string maintenance_name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getMaintenanceName()
    {
        return $this->maintenance_name;
    }

    /**
     * Output only. The name of the maintenance.
     *
     * Generated from protobuf field <code>string maintenance_name = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setMaintenanceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->maintenance_name = $var;

        return $this;
    }

    /**
     * Output only. The title of the maintenance.
     *
     * Generated from protobuf field <code>string title = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Output only. The title of the maintenance.
     *
     * Generated from protobuf field <code>string title = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Output only. The description of the maintenance.
     *
     * Generated from protobuf field <code>string description = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Output only. The description of the maintenance.
     *
     * Generated from protobuf field <code>string description = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Output only. The category of the maintenance event.
     *
     * Generated from protobuf field <code>.google.cloud.maintenance.api.v1.MaintenanceCategory category = 13 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Output only. The category of the maintenance event.
     *
     * Generated from protobuf field <code>.google.cloud.maintenance.api.v1.MaintenanceCategory category = 13 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Maintenance\Api\V1\MaintenanceCategory::class);
        $this->category = $var;

        return $this;
    }

    /**
     * Output only. Scheduled start time of the maintenance. The maintenance will
     * start at `maintenanceScheduledStartTime` or later, with best effort to
     * finish before `maintenanceScheduledEndTime`.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_scheduled_start_time = 6 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getMaintenanceScheduledStartTime()
    {
        return $this->maintenance_scheduled_start_time;
    }

    public function hasMaintenanceScheduledStartTime()
    {
        return isset($this->maintenance_scheduled_start_time);
    }

    public function clearMaintenanceScheduledStartTime()
    {
        unset($this->maintenance_scheduled_start_time);
    }

    /**
     * Output only. Scheduled start time of the maintenance. The maintenance will
     * start at `maintenanceScheduledStartTime` or later, with best effort to
     * finish before `maintenanceScheduledEndTime`.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_scheduled_start_time = 6 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setMaintenanceScheduledStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->maintenance_scheduled_start_time = $var;

        return $this;
    }

    /**
     * Output only. An estimated (best effort, not guaranteed) end time of the
     * scheduled maintenance.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_scheduled_end_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getMaintenanceScheduledEndTime()
    {
        return $this->maintenance_scheduled_end_time;
    }

    public function hasMaintenanceScheduledEndTime()
    {
        return isset($this->maintenance_scheduled_end_time);
    }

    public function clearMaintenanceScheduledEndTime()
    {
        unset($this->maintenance_scheduled_end_time);
    }

    /**
     * Output only. An estimated (best effort, not guaranteed) end time of the
     * scheduled maintenance.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_scheduled_end_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setMaintenanceScheduledEndTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->maintenance_scheduled_end_time = $var;

        return $this;
    }

    /**
     * Output only. Actual date when the maintenance started. Field present only
     * after the state changed to `RUNNING`.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_start_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getMaintenanceStartTime()
    {
        return $this->maintenance_start_time;
    }

    public function hasMaintenanceStartTime()
    {
        return isset($this->maintenance_start_time);
    }

    public function clearMaintenanceStartTime()
    {
        unset($this->maintenance_start_time);
    }

    /**
     * Output only. Actual date when the maintenance started. Field present only
     * after the state changed to `RUNNING`.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_start_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setMaintenanceStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->maintenance_start_time = $var;

        return $this;
    }

    /**
     * Output only. Actual date when the maintenance successfully completed. Field
     * present only after the state changed to `SUCCEEDED`.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_end_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getMaintenanceEndTime()
    {
        return $this->maintenance_end_time;
    }

    public function hasMaintenanceEndTime()
    {
        return isset($this->maintenance_end_time);
    }

    public function clearMaintenanceEndTime()
    {
        unset($this->maintenance_end_time);
    }

    /**
     * Output only. Actual date when the maintenance successfully completed. Field
     * present only after the state changed to `SUCCEEDED`.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp maintenance_end_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setMaintenanceEndTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->maintenance_end_time = $var;

        return $this;
    }

    /**
     * Output only. Indicates whether the user has some control over that
     * maintenance, either proactively before maintenance was scheduled with
     * maintenance policy or with reactive controls after it was scheduled (see
     * controls field).
     *
     * Generated from protobuf field <code>bool user_controllable = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return bool
     */
    public function getUserControllable()
    {
        return $this->user_controllable;
    }

    /**
     * Output only. Indicates whether the user has some control over that
     * maintenance, either proactively before maintenance was scheduled with
     * maintenance policy or with reactive controls after it was scheduled (see
     * controls field).
     *
     * Generated from protobuf field <code>bool user_controllable = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param bool $var
     * @return $this
     */
    public function setUserControllable($var)
    {
        GPBUtil::checkBool($var);
        $this->user_controllable = $var;

        return $this;
    }

    /**
     * Output only. Control available for that Maintenance (might not be available
     * for every resource that maintenance is applied to).
     *
     * Generated from protobuf field <code>repeated .google.cloud.maintenance.api.v1.MaintenanceControl controls = 14 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getControls()
    {
        return $this->controls;
    }

    /**
     * Output only. Control available for that Maintenance (might not be available
     * for every resource that maintenance is applied to).
     *
     * Generated from protobuf field <code>repeated .google.cloud.maintenance.api.v1.MaintenanceControl controls = 14 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param array<\Google\Cloud\Maintenance\Api\V1\MaintenanceControl>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setControls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Maintenance\Api\V1\MaintenanceControl::class);
        $this->controls = $arr;

        return $this;
    }

    /**
     * Output only. Stats is a field of ResourceMaintenance used to aggregate the
     * stats.
     *
     * Generated from protobuf field <code>repeated .google.cloud.maintenance.api.v1.MaintenanceSummary.Stats stats = 12 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Output only. Stats is a field of ResourceMaintenance used to aggregate the
     * stats.
     *
     * Generated from protobuf field <code>repeated .google.cloud.maintenance.api.v1.MaintenanceSummary.Stats stats = 12 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param array<\Google\Cloud\Maintenance\Api\V1\MaintenanceSummary\Stats>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Maintenance\Api\V1\MaintenanceSummary\Stats::class);
        $this->stats = $arr;

        return $this;
    }

}

