<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/analytics/data/v1alpha/analytics_data_api.proto

namespace Google\Analytics\Data\V1alpha;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A request to return the PropertyQuotasSnapshot for a given category.
 *
 * Generated from protobuf message <code>google.analytics.data.v1alpha.GetPropertyQuotasSnapshotRequest</code>
 */
class GetPropertyQuotasSnapshotRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. Quotas from this property will be listed in the response.
     * Format: `properties/{property}/propertyQuotasSnapshot`
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $name = '';

    /**
     * @param string $name Required. Quotas from this property will be listed in the response.
     *                     Format: `properties/{property}/propertyQuotasSnapshot`
     *                     Please see {@see AlphaAnalyticsDataClient::propertyQuotasSnapshotName()} for help formatting this field.
     *
     * @return \Google\Analytics\Data\V1alpha\GetPropertyQuotasSnapshotRequest
     *
     * @experimental
     */
    public static function build(string $name): self
    {
        return (new self())
            ->setName($name);
    }

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Required. Quotas from this property will be listed in the response.
     *           Format: `properties/{property}/propertyQuotasSnapshot`
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Analytics\Data\V1Alpha\AnalyticsDataApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. Quotas from this property will be listed in the response.
     * Format: `properties/{property}/propertyQuotasSnapshot`
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Required. Quotas from this property will be listed in the response.
     * Format: `properties/{property}/propertyQuotasSnapshot`
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

