<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/admanager/v1/rich_media_studio_creative_billing_attribute_enum.proto

namespace Google\Ads\AdManager\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Wrapper message for
 * [RichMediaStudioCreativeBillingAttribute][google.ads.admanager.v1.RichMediaStudioCreativeBillingAttributeEnum.RichMediaStudioCreativeBillingAttribute]
 *
 * Generated from protobuf message <code>google.ads.admanager.v1.RichMediaStudioCreativeBillingAttributeEnum</code>
 */
class RichMediaStudioCreativeBillingAttributeEnum extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Ads\Admanager\V1\RichMediaStudioCreativeBillingAttributeEnum::initOnce();
        parent::__construct($data);
    }

}

