<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/chat/v1/widgets.proto

namespace Google\Apps\Chat\V1\WidgetMarkup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A button with text and `onclick` action.
 *
 * Generated from protobuf message <code>google.chat.v1.WidgetMarkup.TextButton</code>
 */
class TextButton extends \Google\Protobuf\Internal\Message
{
    /**
     * The text of the button.
     *
     * Generated from protobuf field <code>string text = 1;</code>
     */
    protected $text = '';
    /**
     * The `onclick` action of the button.
     *
     * Generated from protobuf field <code>.google.chat.v1.WidgetMarkup.OnClick on_click = 2;</code>
     */
    protected $on_click = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $text
     *           The text of the button.
     *     @type \Google\Apps\Chat\V1\WidgetMarkup\OnClick $on_click
     *           The `onclick` action of the button.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Chat\V1\Widgets::initOnce();
        parent::__construct($data);
    }

    /**
     * The text of the button.
     *
     * Generated from protobuf field <code>string text = 1;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * The text of the button.
     *
     * Generated from protobuf field <code>string text = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * The `onclick` action of the button.
     *
     * Generated from protobuf field <code>.google.chat.v1.WidgetMarkup.OnClick on_click = 2;</code>
     * @return \Google\Apps\Chat\V1\WidgetMarkup\OnClick|null
     */
    public function getOnClick()
    {
        return $this->on_click;
    }

    public function hasOnClick()
    {
        return isset($this->on_click);
    }

    public function clearOnClick()
    {
        unset($this->on_click);
    }

    /**
     * The `onclick` action of the button.
     *
     * Generated from protobuf field <code>.google.chat.v1.WidgetMarkup.OnClick on_click = 2;</code>
     * @param \Google\Apps\Chat\V1\WidgetMarkup\OnClick $var
     * @return $this
     */
    public function setOnClick($var)
    {
        GPBUtil::checkMessage($var, \Google\Apps\Chat\V1\WidgetMarkup\OnClick::class);
        $this->on_click = $var;

        return $this;
    }

}


