<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/identity/accesscontextmanager/v1/service_perimeter.proto

namespace Google\Identity\AccessContextManager\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Identity\AccessContextManager\V1\ServicePerimeterConfig\IngressFrom instead.
     * @deprecated
     */
    class ServicePerimeterConfig_IngressFrom {}
}
class_exists(ServicePerimeterConfig\IngressFrom::class);
@trigger_error('Google\Identity\AccessContextManager\V1\ServicePerimeterConfig_IngressFrom is deprecated and will be removed in a future release. Use Google\Identity\AccessContextManager\V1\ServicePerimeterConfig\IngressFrom instead', E_USER_DEPRECATED);

