deep-copy-regex:
- source: /google/api/google-api-php/(.*)
  dest: /owl-bot-staging/CommonProtos/api/$1
- source: /google/cloud/extended-operations-php/(.*)
  dest: /owl-bot-staging/CommonProtos/extendedoperations/$1
- source: /google/cloud/location/.*-php/(.*)
  dest: /owl-bot-staging/CommonProtos/location/$1
- source: /google/iam/v1/.*-php/(.*)
  dest: /owl-bot-staging/CommonProtos/iam/$1
- source: /google/iam/v1/logging/.*-php/(.*)
  dest: /owl-bot-staging/CommonProtos/iamlogging/$1
- source: /google/logging/type/.*-php/(.*)
  dest: /owl-bot-staging/CommonProtos/logging/$1
- source: /google/rpc/.*-php/(.*)
  dest: /owl-bot-staging/CommonProtos/rpc/$1
- source: /google/type/.*-php/(.*)
  dest: /owl-bot-staging/CommonProtos/type/$1
api-name: CommonProtos
