deep-copy-regex:
    - source: /google/shopping/merchant/ordertracking/(v1beta|v1)/.*-php/(.*)
      dest: /owl-bot-staging/ShoppingMerchantOrderTracking/$1/$2
api-name: ShoppingMerchantOrderTracking
