<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/contactcenterinsights/v1/resources.proto

namespace Google\Cloud\ContactCenterInsights\V1\AnnotatorSelector;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Configuration for summarization.
 *
 * Generated from protobuf message <code>google.cloud.contactcenterinsights.v1.AnnotatorSelector.SummarizationConfig</code>
 */
class SummarizationConfig extends \Google\Protobuf\Internal\Message
{
    protected $model_source;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $conversation_profile
     *           Resource name of the Dialogflow conversation profile.
     *           Format:
     *           projects/{project}/locations/{location}/conversationProfiles/{conversation_profile}
     *     @type int $summarization_model
     *           Default summarization model to be used.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Contactcenterinsights\V1\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name of the Dialogflow conversation profile.
     * Format:
     * projects/{project}/locations/{location}/conversationProfiles/{conversation_profile}
     *
     * Generated from protobuf field <code>string conversation_profile = 1 [(.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getConversationProfile()
    {
        return $this->readOneof(1);
    }

    public function hasConversationProfile()
    {
        return $this->hasOneof(1);
    }

    /**
     * Resource name of the Dialogflow conversation profile.
     * Format:
     * projects/{project}/locations/{location}/conversationProfiles/{conversation_profile}
     *
     * Generated from protobuf field <code>string conversation_profile = 1 [(.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setConversationProfile($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Default summarization model to be used.
     *
     * Generated from protobuf field <code>.google.cloud.contactcenterinsights.v1.AnnotatorSelector.SummarizationConfig.SummarizationModel summarization_model = 2;</code>
     * @return int
     */
    public function getSummarizationModel()
    {
        return $this->readOneof(2);
    }

    public function hasSummarizationModel()
    {
        return $this->hasOneof(2);
    }

    /**
     * Default summarization model to be used.
     *
     * Generated from protobuf field <code>.google.cloud.contactcenterinsights.v1.AnnotatorSelector.SummarizationConfig.SummarizationModel summarization_model = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSummarizationModel($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\ContactCenterInsights\V1\AnnotatorSelector\SummarizationConfig\SummarizationModel::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getModelSource()
    {
        return $this->whichOneof("model_source");
    }

}


