<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/orchestration/airflow/service/v1/environments.proto

namespace Google\Cloud\Orchestration\Airflow\Service\V1\ListWorkloadsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Workload status.
 *
 * Generated from protobuf message <code>google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkloadStatus</code>
 */
class ComposerWorkloadStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Output only. Workload state.
     *
     * Generated from protobuf field <code>.google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkloadState state = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $state = 0;
    /**
     * Output only. Text to provide more descriptive status.
     *
     * Generated from protobuf field <code>string status_message = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $status_message = '';
    /**
     * Output only. Detailed message of the status.
     *
     * Generated from protobuf field <code>string detailed_status_message = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $detailed_status_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $state
     *           Output only. Workload state.
     *     @type string $status_message
     *           Output only. Text to provide more descriptive status.
     *     @type string $detailed_status_message
     *           Output only. Detailed message of the status.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Orchestration\Airflow\Service\V1\Environments::initOnce();
        parent::__construct($data);
    }

    /**
     * Output only. Workload state.
     *
     * Generated from protobuf field <code>.google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkloadState state = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Output only. Workload state.
     *
     * Generated from protobuf field <code>.google.cloud.orchestration.airflow.service.v1.ListWorkloadsResponse.ComposerWorkloadState state = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Orchestration\Airflow\Service\V1\ListWorkloadsResponse\ComposerWorkloadState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Output only. Text to provide more descriptive status.
     *
     * Generated from protobuf field <code>string status_message = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getStatusMessage()
    {
        return $this->status_message;
    }

    /**
     * Output only. Text to provide more descriptive status.
     *
     * Generated from protobuf field <code>string status_message = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setStatusMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->status_message = $var;

        return $this;
    }

    /**
     * Output only. Detailed message of the status.
     *
     * Generated from protobuf field <code>string detailed_status_message = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getDetailedStatusMessage()
    {
        return $this->detailed_status_message;
    }

    /**
     * Output only. Detailed message of the status.
     *
     * Generated from protobuf field <code>string detailed_status_message = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setDetailedStatusMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->detailed_status_message = $var;

        return $this;
    }

}


