deep-copy-regex:
    - source: /google/cloud/beyondcorp/clientconnectorservices/(v1)/.*-php/(.*)
      dest: /owl-bot-staging/BeyondCorpClientConnectorServices/$1/$2
api-name: BeyondCorpClientConnectorServices
