<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/securitycenter/v2/simulation.proto

namespace GPBMetadata\Google\Cloud\Securitycenter\V2;

class Simulation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Cloud\Securitycenter\V2\Resource::initOnce();
        \GPBMetadata\Google\Cloud\Securitycenter\V2\ValuedResource::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB3\x07\x0A/google/cloud/securitycenter/v2/simulation.proto\x12\x1Egoogle.cloud.securitycenter.v2\x1A\x19google/api/resource.proto\x1A-google/cloud/securitycenter/v2/resource.proto\x1A4google/cloud/securitycenter/v2/valued_resource.proto\x1A\x1Fgoogle/protobuf/timestamp.proto\"\xCA\x03\x0A\x0ASimulation\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x124\x0A\x0Bcreate_time\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampB\x03\xE0A\x03\x12d\x0A\x1Fresource_value_configs_metadata\x18\x03 \x03(\x0B2;.google.cloud.securitycenter.v2.ResourceValueConfigMetadata\x12E\x0A\x0Ecloud_provider\x18\x04 \x01(\x0E2-.google.cloud.securitycenter.v2.CloudProvider:\xCA\x01\xEAA\xC6\x01\x0A(securitycenter.googleapis.com/Simulation\x125organizations/{organization}/simulations/{simulation}\x12Jorganizations/{organization}/locations/{location}/simulations/{simluation}*\x0Bsimulations2\x0AsimulationB\xE9\x01\x0A\"com.google.cloud.securitycenter.v2B\x0FSimulationProtoP\x01ZJcloud.google.com/go/securitycenter/apiv2/securitycenterpb;securitycenterpb\xAA\x02\x1EGoogle.Cloud.SecurityCenter.V2\xCA\x02\x1EGoogle\\Cloud\\SecurityCenter\\V2\xEA\x02!Google::Cloud::SecurityCenter::V2b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

