<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/ces/v1/conversation.proto

namespace Google\Cloud\Ces\V1\Conversation;

use UnexpectedValueException;

/**
 * The channel type of the conversation.
 *
 * Protobuf type <code>google.cloud.ces.v1.Conversation.ChannelType</code>
 */
class ChannelType
{
    /**
     * Unspecified channel type.
     *
     * Generated from protobuf enum <code>CHANNEL_TYPE_UNSPECIFIED = 0;</code>
     */
    const CHANNEL_TYPE_UNSPECIFIED = 0;
    /**
     * The conversation only contains text messages between the end user and the
     * agent.
     *
     * Generated from protobuf enum <code>TEXT = 1;</code>
     */
    const TEXT = 1;
    /**
     * The conversation contains audio messages between the end user and the
     * agent.
     *
     * Generated from protobuf enum <code>AUDIO = 2;</code>
     */
    const AUDIO = 2;
    /**
     * The conversation multi-modal messages (e.g. image) between the end user
     * and the agent.
     *
     * Generated from protobuf enum <code>MULTIMODAL = 3;</code>
     */
    const MULTIMODAL = 3;

    private static $valueToName = [
        self::CHANNEL_TYPE_UNSPECIFIED => 'CHANNEL_TYPE_UNSPECIFIED',
        self::TEXT => 'TEXT',
        self::AUDIO => 'AUDIO',
        self::MULTIMODAL => 'MULTIMODAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}


