<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow/cx/v3/transition_route_group.proto

namespace GPBMetadata\Google\Cloud\Dialogflow\Cx\V3;

class TransitionRouteGroup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Cloud\Dialogflow\Cx\V3\Page::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\FieldMask::initOnce();
        $pool->internalAddGeneratedFile(
            '
ì
:google/cloud/dialogflow/cx/v3/transition_route_group.protogoogle.cloud.dialogflow.cx.v3google/api/client.protogoogle/api/field_behavior.protogoogle/api/resource.proto(google/cloud/dialogflow/cx/v3/page.protogoogle/protobuf/empty.proto google/protobuf/field_mask.proto"É
TransitionRouteGroup
name (	
display_name (	BàAI
transition_routes (2..google.cloud.dialogflow.cx.v3.TransitionRoute:¼êA¸
.dialogflow.googleapis.com/TransitionRouteGrouprprojects/{project}/locations/{location}/agents/{agent}/flows/{flow}/transitionRouteGroups/{transition_route_group}eprojects/{project}/locations/{location}/agents/{agent}/transitionRouteGroups/{transition_route_group}*transitionRouteGroups2transitionRouteGroup"¨
 ListTransitionRouteGroupsRequestF
parent (	B6àAúA0.dialogflow.googleapis.com/TransitionRouteGroup
	page_size (

page_token (	
language_code (	"’
!ListTransitionRouteGroupsResponseT
transition_route_groups (23.google.cloud.dialogflow.cx.v3.TransitionRouteGroup
next_page_token (	"}
GetTransitionRouteGroupRequestD
name (	B6àAúA0
.dialogflow.googleapis.com/TransitionRouteGroup
language_code (	"Ü
!CreateTransitionRouteGroupRequestF
parent (	B6àAúA0.dialogflow.googleapis.com/TransitionRouteGroupX
transition_route_group (23.google.cloud.dialogflow.cx.v3.TransitionRouteGroupBàA
language_code (	"Å
!UpdateTransitionRouteGroupRequestX
transition_route_group (23.google.cloud.dialogflow.cx.v3.TransitionRouteGroupBàA/
update_mask (2.google.protobuf.FieldMask
language_code (	"x
!DeleteTransitionRouteGroupRequestD
name (	B6àAúA0
.dialogflow.googleapis.com/TransitionRouteGroup
force (2Ý
TransitionRouteGroupsÃ
ListTransitionRouteGroups?.google.cloud.dialogflow.cx.v3.ListTransitionRouteGroupsRequest@.google.cloud.dialogflow.cx.v3.ListTransitionRouteGroupsResponse"¢ÚAparent‚Óä“’J/v3/{parent=projects/*/locations/*/agents/*/flows/*}/transitionRouteGroupsZDB/v3/{parent=projects/*/locations/*/agents/*}/transitionRouteGroups°
GetTransitionRouteGroup=.google.cloud.dialogflow.cx.v3.GetTransitionRouteGroupRequest3.google.cloud.dialogflow.cx.v3.TransitionRouteGroup" ÚAname‚Óä“’J/v3/{name=projects/*/locations/*/agents/*/flows/*/transitionRouteGroups/*}ZDB/v3/{name=projects/*/locations/*/agents/*/transitionRouteGroups/*}ÿ
CreateTransitionRouteGroup@.google.cloud.dialogflow.cx.v3.CreateTransitionRouteGroupRequest3.google.cloud.dialogflow.cx.v3.TransitionRouteGroup"éÚAparent,transition_route_group‚Óä“Â"J/v3/{parent=projects/*/locations/*/agents/*/flows/*}/transitionRouteGroups:transition_route_groupZ\\"B/v3/{parent=projects/*/locations/*/agents/*}/transitionRouteGroups:transition_route_group²
UpdateTransitionRouteGroup@.google.cloud.dialogflow.cx.v3.UpdateTransitionRouteGroupRequest3.google.cloud.dialogflow.cx.v3.TransitionRouteGroup"œÚA"transition_route_group,update_mask‚Óä“ð2a/v3/{transition_route_group.name=projects/*/locations/*/agents/*/flows/*/transitionRouteGroups/*}:transition_route_groupZs2Y/v3/{transition_route_group.name=projects/*/locations/*/agents/*/transitionRouteGroups/*}:transition_route_group™
DeleteTransitionRouteGroup@.google.cloud.dialogflow.cx.v3.DeleteTransitionRouteGroupRequest.google.protobuf.Empty" ÚAname‚Óä“’*J/v3/{name=projects/*/locations/*/agents/*/flows/*/transitionRouteGroups/*}ZD*B/v3/{name=projects/*/locations/*/agents/*/transitionRouteGroups/*}xÊAdialogflow.googleapis.comÒAYhttps://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/dialogflowB¼
!com.google.cloud.dialogflow.cx.v3BTransitionRouteGroupProtoPZ1cloud.google.com/go/dialogflow/cx/apiv3/cxpb;cxpb¢DFªGoogle.Cloud.Dialogflow.Cx.V3ê!Google::Cloud::Dialogflow::CX::V3bproto3'
        , true);

        static::$is_initialized = true;
    }
}

