name: Run GAX Conformance Tests With Showcase
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
    gapic-showcase:
        runs-on: ubuntu-latest
        env:
            GAPIC_SHOWCASE_VERSION: 0.40.0
            OS: linux
            ARCH: amd64
        name: GAPIC Showcase Conformance Tests
        steps:
        - name: Checkout code
          uses: actions/checkout@v7

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
            extensions: grpc

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '>=1.26'

        - name: Install GAPIC Showcase from Branch
          run: |
            go install github.com/googleapis/gapic-showcase@feat-pqc-tls

        - name: Run the GAPIC showcase server
          run: |
            gapic-showcase run --port :7469 --tls --ca-cert-output-file showcase.pem & sleep 5

        - name: Install dependencies
          run: |
            composer update --prefer-dist --no-interaction --no-suggest -d Gax/

        - name: Run PHPUnit
          run: Gax/vendor/bin/phpunit -c Gax/phpunit-conformance.xml.dist
