name: Run Datastore System Tests With Emulator
on:
  push:
    branches:
      - main
    paths:
      - 'Datastore/**'
      - '.github/workflows/datastore-emulator-system-tests.yaml'
      - '.github/emulator/**'
  pull_request:
    paths:
      - 'Datastore/**'
      - '.github/workflows/datastore-emulator-system-tests.yaml'
      - '.github/emulator/**'
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: ./.github/emulator/start-emulator.sh datastore 419.0.0-emulators

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: pecl
          extensions: grpc

      - name: Install dependencies
        run: |
          composer config minimum-stability dev -d Datastore/
          composer config repositories.local path "../Core" -d Datastore
          composer require "google/cloud-core:*" -d Datastore/

      - name: Run system tests
        run: |
          Datastore/vendor/bin/phpunit -c Datastore/phpunit-system.xml.dist
        env:
          DATASTORE_EMULATOR_HOST: localhost:8085
          GOOGLE_CLOUD_PHP_TESTS_KEY_PATH: '.github/emulator/example-key.json'
          GOOGLE_CLOUD_PHP_WHITELIST_TESTS_KEY_PATH: '.github/emulator/example-key.json'
