name: DocFX Test Suite

permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  docfx:
    name: "Run DocFX tests"
    runs-on: ubuntu-latest
    env:
      PHPDOC_ENV: prod
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        persist-credentials: false
    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      with:
        python-version: '3.14'
    - run: pip install --no-deps --require-hashes -r .kokoro/docs/docker/requirements.txt
    - name: Setup PHP
      uses: shivammathur/setup-php@verbose # zizmor: ignore[unpinned-uses]
      with:
        php-version: "8.2"
    - name: Extract phpDocumentor
      id: extract
      uses: shrink/actions-docker-extract@f1ef61065b78731fe3310b4e84e511f6a927a77e # v4
      with:
        image: "phpdoc/phpdoc:3.5.3"
        path: "/opt/phpdoc/."
    - name: Symlink phpDocumentor
      run: ln -s $(pwd)/${STEPS_EXTRACT_OUTPUTS_DESTINATION}/bin/phpdoc /usr/local/bin/phpdoc
      env:
        STEPS_EXTRACT_OUTPUTS_DESTINATION: ${{ steps.extract.outputs.destination }}
    - name: Install Dependencies
      uses: nick-invision/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: composer --no-interaction --no-ansi --no-progress --no-cache update -d dev
    - name: Run DocFX Unit Test Suite
      run: dev/vendor/bin/phpunit -c dev/phpunit-docfx.xml.dist
    - name: Run Docs Generator (Dry Run)
      run: .kokoro/docs/publish.sh
