name: DocFX Test Suite
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docfx:
    name: "Run DocFX tests"
    runs-on: ubuntu-latest
    env:
      PHPDOC_ENV: prod
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.14'
      - run: pip install --require-hashes -r .kokoro/docs/docker/requirements.txt
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: "8.2"
      - name: Extract phpDocumentor
        id: extract
        uses: shrink/actions-docker-extract@f1ef61065b78731fe3310b4e84e511f6a927a77e # v4
        with:
          image: "phpdoc/phpdoc:3.5.3"
          path: "/opt/phpdoc/."
      - name: Symlink phpDocumentor
        run: ln -s $(pwd)/${STEPS_EXTRACT_OUTPUTS_DESTINATION}/bin/phpdoc /usr/local/bin/phpdoc
        env:
          STEPS_EXTRACT_OUTPUTS_DESTINATION: ${{ steps.extract.outputs.destination }}
      - name: Install Dependencies
        uses: nick-invision/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: composer --no-interaction --no-ansi --no-progress update -d dev
      - name: Run DocFX Unit Test Suite
        run: dev/vendor/bin/phpunit -c dev/phpunit-docfx.xml.dist
      - name: Install Dependencies (--no-dev)
        uses: nick-invision/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: composer --no-interaction --no-ansi --no-progress --no-dev update -d dev
      - name: Run Docs Generator (Dry Run)
        run: .kokoro/docs/publish.sh
