on:
  push:
    branches:
      - main
    paths:
      - 'Firestore/**'
      - '.github/workflows/firestore-emulator-system-tests.yaml'
      - '.github/emulator/**'
  pull_request:
    paths:
      - 'Firestore/**'
      - '.github/workflows/firestore-emulator-system-tests.yaml'
      - '.github/emulator/**'
name: Run Firestore System Tests With Emulator
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - run: ./.github/emulator/start-emulator.sh firestore 424.0.0-emulators

      - name: Setup PHP
        uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d # v2
        with:
          php-version: '7.4'
          tools: pecl
          extensions: grpc-1.49.0

      - name: Install dependencies
        run: |
          composer config minimum-stability dev -d Firestore/
          composer config repositories.local path "../Core" -d Firestore
          composer require "google/cloud-core:*" -d Firestore/

      - name: Run system tests
        run: |
          Firestore/vendor/bin/phpunit -c Firestore/phpunit-system.xml.dist --exclude-group gapic
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8085
          GOOGLE_CLOUD_PHP_TESTS_KEY_PATH: '.github/emulator/example-key.json'
          GOOGLE_CLOUD_PHP_WHITELIST_TESTS_KEY_PATH: '.github/emulator/example-key.json'
