name: CS Test Suite
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
jobs:
  style:
    runs-on: ubuntu-latest
    name: PHP Style Check
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: "Install dependencies"
      run: composer global require "squizlabs/php_codesniffer:3.*"
    - name: Run PHPCS Code Style Checker
      run: ~/.composer/vendor/bin/phpcs --standard=phpcs-ruleset.xml -p
