name: CS Test Suite
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
jobs:
  style:
    runs-on: ubuntu-latest
    name: PHP Style Check
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install Dependencies
      run: composer global require "squizlabs/php_codesniffer:3.*"
    - name: Run PHPCS Code Style Checker
      run: ~/.composer/vendor/bin/phpcs --standard=phpcs-ruleset.xml -p

  style2:
    name: PHP CS Fixer
    uses: GoogleCloudPlatform/php-tools/.github/workflows/code-standards.yml@exclude-patterns
    with:
      config: GoogleCloudPlatform/php-tools/.php-cs-fixer.default.php@exclude-patterns
      exclude-patterns: |
        [
          "*/samples",
          "*/src/V[0-9]+",
          "*/src/*/V[0-9]+",
          "*/src/*/*/V[0-9]+",
          "*/tests/*/V[0-9]+",
          "*/tests/*/*/V[0-9]+",
          "AccessContextManager/src/Type",
          "Asset/external",
          "BigQueryDataExchange/src/Common",
          "Core/src/Testing",
          "GSuiteAddOns/external",
          "OsLogin/src/Common",
          "LongRunning/src/ApiCore/LongRunning",
          "LongRunning/src/LongRunning",
          "vendor",
          "dev",
          "docs",
          "*/metadata",
          "Firestore/tests/Conformance",
          "tests/Component/TestComposerInstall.php",
          "CommonProtos",
          "Translate/src/TranslateClient.php",
          "Translate/src/Connection/*"
        ]

  staticanalysis:
    runs-on: ubuntu-latest
    name: PHPStan Static Analysis
    steps:
    - uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: "Install dependencies"
      run: |
        composer --no-interaction --no-ansi --no-progress update
        composer --no-interaction --no-ansi --no-progress update -d dev
    - name: Run Static Analysis
      run: |
        dev/sh/static-analysis
