name: CS Test Suite
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  style:
    runs-on: ubuntu-latest
    name: PHP Style Check
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - name: Setup PHP
      uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d # v2
      with:
        php-version: '8.0'
    - name: "Install dependencies"
      run: composer global require "squizlabs/php_codesniffer:3.*"
    - name: Run PHPCS Code Style Checker
      run: ~/.composer/vendor/bin/phpcs --standard=phpcs-ruleset.xml -p
