name: Test Suite
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-latest
    name: PHP Style Check
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Install Dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: composer --no-interaction --no-ansi --no-progress update
    - name: Run PHPCS Code Style Checker
      run: dev/sh/style

  staticanalysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Run Static Analysis
      run: |
        composer require --dev phpstan/phpstan:^1.7
        dev/sh/static-analysis
