name: CS Test Suite
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
jobs:
  style:
    runs-on: ubuntu-latest
    name: PHP Style Check
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install Dependencies
      run: composer global require "squizlabs/php_codesniffer:3.*"
    - name: Run PHPCS Code Style Checker
      run: ~/.composer/vendor/bin/phpcs --standard=phpcs-ruleset.xml -p
  staticanalysis:
    runs-on: ubuntu-latest
    name: PHPStan Static Analysis
    steps:
    - uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: "Install dependencies"
      run: |
        composer --no-interaction --no-ansi --no-progress update
        composer --no-interaction --no-ansi --no-progress update -d dev
    - name: Run Static Analysis
      run: |
        dev/sh/static-analysis
