name: OwlBot Checks
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: ['main']
jobs:
  # Ensure that PRs labeled "feat" actually contain a new feature, PRs labeled
  # "bug" or "chore" do not.
  # More info at https://github.com/Roave/BackwardCompatibilityCheck.
  conventional-commit-check:
    name: Conventional Commit Check
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'gcf-owl-bot[bot]'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: "Install dependencies"
        run: composer global require "roave/backward-compatibility-check:^8.2"
      - name: "Check for an incorrect feat label in the PR"
        id: compatibility-checker
        continue-on-error: true
        # OwlBot PRs which are not labelled feat should not add new files or methods
        run: |
          ~/.composer/vendor/bin/roave-backward-compatibility-check \
            --from=origin/${{ github.head_ref || github.ref_name }} \
            --to=origin/main
      - name: "Print the action item"
        run: |
          if [[ "${{ steps.compatibility-checker.outcome }}" == 'failure' ]]; then
            if [[ "${{ startsWith(github.event.pull_request.title, 'feat') }}" == "false" ]]; then
              echo "Action item: Change the conventional commit to use 'feat'"
              exit 1
            fi
          elif [[ "${{ startsWith(github.event.pull_request.title, 'feat') }}" == "true" ]]; then
            echo "Action item: No features found, do not use 'feat' for the conventional commit"
            exit 1
          fi

  # Ensure the "owl-bot-staging" directory doesn't exist
  owl-bot-staging-directory-check:
    name: owl-bot-staging check
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'gcf-owl-bot[bot]' && github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v5
      - name: Ensure
        run: |
          directory_to_check="owl-bot-staging"
          if [ -d "$directory_to_check" ]; then
            echo "Error: Directory '$directory_to_check' already exists."
            exit 1
          fi
          echo "Directory '$directory_to_check' does not exist."
