name: Release Components
on:
    push:
        tags:
            - "*"
    workflow_dispatch:
permissions:
  contents: read

jobs:
    docs:
        name: "Split and Release Components"
        runs-on: ubuntu-latest
        steps:
        - name: Harden Runner
          uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
          with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

        - name: Checkout
          uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
          with:
            persist-credentials: false
            fetch-depth: 0
        - name: Setup PHP
          uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d # v2
          with:
            php-version: '7.4'
            ini-values: memory_limit=2048M
        - name: Install Dependencies
          uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # v2.8.3
          with:
            timeout_minutes: 10
            max_attempts: 3
            command: composer update
        - id: getTag
          name: Get Tag
          run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        - name: Run Subtree Split and Release
          env:
            tagName: ${{ steps.getTag.outputs.tag }}
          run: |
            ./dev/google-cloud split $GITHUB_REPOSITORY $tagName -t ${{ secrets.SPLIT_TOKEN }}
