name: Release Components
on:
    push:
        tags:
            - "*"

jobs:
    docs:
        name: "Split and Release Components"
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            persist-credentials: false
            fetch-depth: 0
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'
            ini-values: memory_limit=2048M
        - name: Install Dependencies
          uses: nick-invision/retry@v1
          with:
            timeout_minutes: 10
            max_attempts: 3
            command: composer update
        - id: getTag
          name: Get Tag
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        - name: Run Subtree Split and Release
          env:
            tagName: ${{ steps.getTag.outputs.tag }}
          run: |
            ./dev/google-cloud split $GITHUB_REPOSITORY $tagName -t ${{ secrets.SPLIT_TOKEN }}
