name: Release Components
on:
    push:
        tags:
            - "*"
    workflow_dispatch:

permissions:
    contents: read
jobs:
    docs:
        name: "Split and Release Components"
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            persist-credentials: false
            fetch-depth: 0
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            ini-values: memory_limit=2048M
        - name: Install Dependencies
          uses: nick-fields/retry@v2
          with:
            timeout_minutes: 10
            max_attempts: 3
            command: composer update -d dev
        - id: getTag
          name: Get Tag
          run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        - name: Run Subtree Split and Release
          env:
            tagName: ${{ steps.getTag.outputs.tag }}
          run: |
            ./dev/google-cloud split $GITHUB_REPOSITORY $tagName \
              -t ${{ secrets.SPLIT_TOKEN }} \
              --packagist-username=${{ vars.PACKAGIST_USERNAME }}
              --packagist-token=${{ secrets.PACKAGIST_TOKEN }}
